package saturation

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/platform/dashboardcfg"
)

func queueTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "queue",
		PageID: "saturation",
		Label:  "Message Queue",
		Order:  30,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "g1-summary", Title: "Production Summary", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "g1", Title: "Production Rate", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g2", Title: "Consumption Rate — by Topic", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g3", Title: "Consumption Rate — by Consumer Group", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g4", Title: "Consumer Lag", Order: 50, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g4-details", Title: "Consumer Lag Details", Order: 55, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
			dashboardcfg.SectionDefinition{ID: "g5", Title: "Consumer Group Rebalancing", Order: 60, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g6", Title: "End-to-End Latency", Order: 70, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g7", Title: "Error Rates", Order: 80, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g8", Title: "Broker / Client Connectivity", Order: 90, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "stat-publish-rate",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "g1-summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/summary-stats", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Produce Rate",
				Description:   "Shows the current aggregate message produce rate across all Kafka topics in messages per second. A sudden drop may indicate producer failures or broker unavailability.",
				TitleIcon:     "ArrowUp",
				ValueField:    "publish_rate_per_sec",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-receive-rate",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "g1-summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/summary-stats", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Consume Rate",
				Description:   "Shows the current aggregate message consume rate across all consumer groups in messages per second. Compare with produce rate to detect growing lag.",
				TitleIcon:     "ArrowDown",
				ValueField:    "receive_rate_per_sec",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-max-lag",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "g1-summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/summary-stats", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Max Consumer Lag",
				Description:   "Shows the highest consumer lag across all consumer groups and partitions. A rising value signals that consumers are falling behind producers.",
				TitleIcon:     "Layers",
				ValueField:    "max_lag",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-publish-p95",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "g1-summary",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/summary-stats", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Produce p95 Latency",
				Description:   "Shows the 95th percentile latency for producing messages to Kafka. Watch for spikes that may indicate broker back-pressure or network issues.",
				TitleIcon:     "Clock",
				ValueField:    "publish_p95_ms",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "produce-rate-by-topic",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g1",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/produce-rate-by-topic", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Message Produce Rate by Topic (msg/s)",
				Description:   "Tracks the per-topic message produce throughput over time. Look for uneven distribution or sudden drops that may signal producer issues on specific topics.",
				TitleIcon:     "TrendingUp",
				GroupByKey:    "topic",
				ValueKey:      "rate_per_sec",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaTopic"), IDField: "topic", TitleField: "topic"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "publish-latency-p95-by-topic",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g1",
				Order:         60,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/publish-latency-by-topic", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Publish Latency p95 by Topic (ms)",
				Description:   "Tracks the 95th percentile publish latency for each topic over time. Spikes on individual topics may indicate partition hotspots or slow broker acknowledgements.",
				TitleIcon:     "Clock",
				GroupByKey:    "topic",
				ValueKey:      "p95_ms",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaTopic"), IDField: "topic", TitleField: "topic"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "consume-rate-by-topic",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g2",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/consume-rate-by-topic", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Message Consume Rate by Topic (msg/s)",
				Description:   "Tracks the per-topic message consume throughput over time. Compare with produce rate to identify topics where consumers are not keeping up.",
				TitleIcon:     "TrendingDown",
				GroupByKey:    "topic",
				ValueKey:      "rate_per_sec",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaTopic"), IDField: "topic", TitleField: "topic"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "receive-latency-p95-by-topic",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g2",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/receive-latency-by-topic", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Receive Latency p95 by Topic (ms)",
				Description:   "Tracks the 95th percentile receive latency for each topic over time. Elevated values may point to slow consumer polling or network congestion.",
				TitleIcon:     "Clock",
				GroupByKey:    "topic",
				ValueKey:      "p95_ms",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaTopic"), IDField: "topic", TitleField: "topic"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "consume-rate-by-group",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g3",
				Order:         90,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/consume-rate-by-group", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Consume Rate by Consumer Group (msg/s)",
				Description:   "Tracks message consumption throughput for each consumer group over time. Uneven rates across groups may indicate processing bottlenecks in specific consumers.",
				TitleIcon:     "Users",
				GroupByKey:    "consumer_group",
				ValueKey:      "rate_per_sec",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaGroup"), IDField: "consumer_group", TitleField: "consumer_group"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "process-rate-by-group",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g3",
				Order:         100,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/process-rate-by-group", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Process Rate by Consumer Group (msg/s)",
				Description:   "Tracks the rate at which each consumer group processes messages after receiving them. A gap between consume and process rates suggests slow message handling logic.",
				TitleIcon:     "Cpu",
				GroupByKey:    "consumer_group",
				ValueKey:      "rate_per_sec",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaGroup"), IDField: "consumer_group", TitleField: "consumer_group"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "lag-by-group",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("wide-chart"),
				SectionID:     "g4",
				Order:         110,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/lag-by-group", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Consumer Lag by Group",
				Description:   "Tracks the total consumer lag for each consumer group over time. Steadily increasing lag indicates consumers cannot keep pace with incoming messages.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "consumer_group",
				ValueKey:      "lag",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaGroup"), IDField: "consumer_group", TitleField: "consumer_group"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "lag-per-partition",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("detail-table"),
				SectionID:     "g4-details",
				Order:         120,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/lag-per-partition", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Consumer Lag per Partition",
				Description:   "Shows lag broken down by topic, partition, and consumer group. Use this to identify hot partitions where a single partition drives the majority of lag.",
				TitleIcon:     "Table",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "consumer_group", Label: "Consumer Group", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(180)},
				},
				DrawerAction: &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaGroup"), IDField: "consumer_group", TitleField: "consumer_group"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "rebalance-rate",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g5",
				Order:         130,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/rebalance-signals", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Rebalance Rate by Group (rebalances/s)",
				Description:   "Tracks consumer group rebalance frequency over time. Frequent rebalances cause processing pauses and may indicate unstable consumers or aggressive session timeouts.",
				TitleIcon:     "RefreshCw",
				GroupByKey:    "consumer_group",
				ValueKey:      "rebalance_rate",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaGroup"), IDField: "consumer_group", TitleField: "consumer_group"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "heartbeat-health",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g5",
				Order:         140,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/rebalance-signals", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Failed Heartbeat Rate by Group (failures/s)",
				Description:   "Tracks the rate of failed consumer heartbeats per group. Rising failures typically precede rebalances and may indicate network issues or overloaded consumers.",
				TitleIcon:     "Activity",
				GroupByKey:    "consumer_group",
				ValueKey:      "failed_heartbeat_rate",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaGroup"), IDField: "consumer_group", TitleField: "consumer_group"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "assigned-partitions",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g5",
				Order:         150,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/rebalance-signals", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Assigned Partitions by Group",
				Description:   "Tracks the number of partitions assigned to each consumer group over time. Sudden changes indicate rebalances; uneven distribution may cause processing skew.",
				TitleIcon:     "LayoutGrid",
				GroupByKey:    "consumer_group",
				ValueKey:      "assigned_partitions",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaGroup"), IDField: "consumer_group", TitleField: "consumer_group"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "e2e-publish-p95",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g6",
				Order:         160,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/e2e-latency", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Produce Latency p95 by Topic (ms)",
				Description:   "Tracks end-to-end produce latency at the 95th percentile for each topic. Sustained increases may signal broker disk pressure or replication delays.",
				TitleIcon:     "Clock",
				GroupByKey:    "topic",
				ValueKey:      "publish_p95_ms",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaTopic"), IDField: "topic", TitleField: "topic"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "e2e-receive-p95",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g6",
				Order:         170,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/e2e-latency", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Receive Latency p95 by Topic (ms)",
				Description:   "Tracks end-to-end receive latency at the 95th percentile for each topic. Watch for divergence across topics that may reveal consumer-side bottlenecks.",
				TitleIcon:     "Clock",
				GroupByKey:    "topic",
				ValueKey:      "receive_p95_ms",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaTopic"), IDField: "topic", TitleField: "topic"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "e2e-process-p95",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g6",
				Order:         180,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/e2e-latency", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Process Latency p95 by Topic (ms)",
				Description:   "Tracks end-to-end message processing latency at the 95th percentile for each topic. High values point to slow downstream processing logic after message consumption.",
				TitleIcon:     "Clock",
				GroupByKey:    "topic",
				ValueKey:      "process_p95_ms",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("kafkaTopic"), IDField: "topic", TitleField: "topic"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "publish-errors",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g7",
				Order:         190,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/publish-errors", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Produce Errors by Error Type (errors/s)",
				Description:   "Tracks producer-side error rates grouped by error type over time. Spikes in specific error types help pinpoint issues like serialization failures or authorization errors.",
				TitleIcon:     "XCircle",
				GroupByKey:    "error_type",
				ValueKey:      "error_rate",
			},
			dashboardcfg.PanelDefinition{
				ID:            "consume-errors",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g7",
				Order:         200,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/consume-errors", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Consume Errors by Error Type (errors/s)",
				Description:   "Tracks consumer-side error rates grouped by error type over time. Watch for deserialization or offset commit failures that may cause message reprocessing.",
				TitleIcon:     "XCircle",
				GroupByKey:    "error_type",
				ValueKey:      "error_rate",
			},
			dashboardcfg.PanelDefinition{
				ID:            "process-errors",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g7",
				Order:         210,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/process-errors", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Process Errors by Error Type (errors/s)",
				Description:   "Tracks message processing error rates grouped by error type over time. Persistent errors suggest bugs in consumer business logic or downstream dependency failures.",
				TitleIcon:     "XCircle",
				GroupByKey:    "error_type",
				ValueKey:      "error_rate",
			},
			dashboardcfg.PanelDefinition{
				ID:            "broker-connections",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g8",
				Order:         220,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/broker-connections", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Open Connections to Brokers",
				Description:   "Tracks the number of active client connections to each Kafka broker over time. A sudden drop may indicate broker unavailability or client connectivity issues.",
				TitleIcon:     "Network",
				GroupByKey:    "broker",
				ValueKey:      "connections",
			},
			dashboardcfg.PanelDefinition{
				ID:            "client-op-duration",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g8",
				Order:         230,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/kafka/client-op-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Client Operation Duration p95 by Operation (ms)",
				Description:   "Tracks the 95th percentile duration for Kafka client operations such as poll, commit, and send. Elevated durations reveal which client operations are contributing to overall latency.",
				TitleIcon:     "Activity",
				GroupByKey:    "operation_name",
				ValueKey:      "p95_ms",
			},
		},
	}
}
