package ai

import dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"

func overviewTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "overview",
		PageID: "ai",
		Label:  "Overview",
		Order:  10,
		Sections: []dashboardcfg.SectionDefinition{
			{ID: "ai-kpis", Title: "Key Metrics", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplateKPIBand},
			{ID: "ai-trends", Title: "Traffic & Latency", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplateTwoUp},
			{ID: "ai-ranking", Title: "Leaders", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplateTwoUp},
		},
		Panels: []dashboardcfg.PanelDefinition{
			{
				ID:            "ai-total-runs",
				PanelType:     dashboardcfg.PanelTypeStatCard,
				LayoutVariant: dashboardcfg.LayoutVariantKPI,
				SectionID:     "ai-kpis",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/overview"},
				Layout:        dashboardcfg.PanelLayout{},
				Title:         "AI Runs",
				TitleIcon:     "Sparkles",
				ValueField:    "total_runs",
				Formatter:     "number",
			},
			{
				ID:            "ai-total-cost",
				PanelType:     dashboardcfg.PanelTypeStatCard,
				LayoutVariant: dashboardcfg.LayoutVariantKPI,
				SectionID:     "ai-kpis",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/overview"},
				Layout:        dashboardcfg.PanelLayout{},
				Title:         "Cost (USD)",
				TitleIcon:     "Coins",
				ValueField:    "total_cost_usd",
				Formatter:     "number",
			},
			{
				ID:            "ai-p95-latency",
				PanelType:     dashboardcfg.PanelTypeStatCard,
				LayoutVariant: dashboardcfg.LayoutVariantKPI,
				SectionID:     "ai-kpis",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/overview"},
				Layout:        dashboardcfg.PanelLayout{},
				Title:         "p95 Latency",
				TitleIcon:     "Clock3",
				ValueField:    "p95_latency_ms",
				Formatter:     "ms",
			},
			{
				ID:            "ai-quality-score",
				PanelType:     dashboardcfg.PanelTypeStatCard,
				LayoutVariant: dashboardcfg.LayoutVariantKPI,
				SectionID:     "ai-kpis",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/overview"},
				Layout:        dashboardcfg.PanelLayout{},
				Title:         "Avg Quality",
				TitleIcon:     "ShieldCheck",
				ValueField:    "avg_quality_score",
				Formatter:     "number",
			},
			{
				ID:            "ai-request-trend",
				PanelType:     dashboardcfg.PanelTypeRequest,
				LayoutVariant: dashboardcfg.LayoutVariantStandardChart,
				SectionID:     "ai-trends",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/overview/timeseries"},
				Layout:        dashboardcfg.PanelLayout{},
				Title:         "AI Run Volume",
				TitleIcon:     "Activity",
				ValueKey:      "requests",
				XKey:          "time_bucket",
			},
			{
				ID:            "ai-latency-trend",
				PanelType:     dashboardcfg.PanelTypeLatency,
				LayoutVariant: dashboardcfg.LayoutVariantStandardChart,
				SectionID:     "ai-trends",
				Order:         60,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/overview/timeseries"},
				Layout:        dashboardcfg.PanelLayout{},
				Title:         "Latency & TTFT",
				TitleIcon:     "Timer",
				ValueKey:      "p95_latency_ms",
				XKey:          "time_bucket",
			},
			{
				ID:            "ai-top-models",
				PanelType:     dashboardcfg.PanelTypeTable,
				LayoutVariant: dashboardcfg.LayoutVariantSummaryTable,
				SectionID:     "ai-ranking",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/overview/top-models"},
				Layout:        dashboardcfg.PanelLayout{},
				Title:         "Top Models",
				TitleIcon:     "Bot",
				Columns: []dashboardcfg.DashboardTableColumn{
					{Key: "provider", Label: "Provider"},
					{Key: "request_model", Label: "Model"},
					{Key: "requests", Label: "Runs", Formatter: "number", Align: dashboardcfg.ColumnAlignRight},
					{Key: "avg_latency_ms", Label: "Avg latency", Formatter: "ms", Align: dashboardcfg.ColumnAlignRight},
					{Key: "total_cost_usd", Label: "Cost", Formatter: "number", Align: dashboardcfg.ColumnAlignRight},
					{Key: "avg_quality_score", Label: "Quality", Formatter: "number", Align: dashboardcfg.ColumnAlignRight},
				},
			},
			{
				ID:            "ai-top-prompts",
				PanelType:     dashboardcfg.PanelTypeTable,
				LayoutVariant: dashboardcfg.LayoutVariantSummaryTable,
				SectionID:     "ai-ranking",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/overview/top-prompts"},
				Layout:        dashboardcfg.PanelLayout{},
				Title:         "Top Prompt Templates",
				TitleIcon:     "FileText",
				Columns: []dashboardcfg.DashboardTableColumn{
					{Key: "prompt_template", Label: "Prompt template"},
					{Key: "prompt_template_version", Label: "Version"},
					{Key: "requests", Label: "Runs", Formatter: "number", Align: dashboardcfg.ColumnAlignRight},
					{Key: "avg_latency_ms", Label: "Avg latency", Formatter: "ms", Align: dashboardcfg.ColumnAlignRight},
					{Key: "total_cost_usd", Label: "Cost", Formatter: "number", Align: dashboardcfg.ColumnAlignRight},
					{Key: "avg_quality_score", Label: "Quality", Formatter: "number", Align: dashboardcfg.ColumnAlignRight},
				},
			},
		},
	}
}
