// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metric_row.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Row is the wire format on Kafka. One record == one metric data point bound
// for observability.metrics. Field order mirrors the ClickHouse column order
// in row.go Columns.
type Row struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TeamId              uint32                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Env                 string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	MetricName          string                 `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricType          string                 `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"` // Gauge | Sum | Histogram
	Temporality         string                 `protobuf:"bytes,5,opt,name=temporality,proto3" json:"temporality,omitempty"`                 // Unspecified | Delta | Cumulative
	IsMonotonic         bool                   `protobuf:"varint,6,opt,name=is_monotonic,json=isMonotonic,proto3" json:"is_monotonic,omitempty"`
	Unit                string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	Description         string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ResourceFingerprint string                 `protobuf:"bytes,9,opt,name=resource_fingerprint,json=resourceFingerprint,proto3" json:"resource_fingerprint,omitempty"`
	TimestampNs         int64                  `protobuf:"varint,10,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Value               float64                `protobuf:"fixed64,11,opt,name=value,proto3" json:"value,omitempty"`
	HistSum             float64                `protobuf:"fixed64,12,opt,name=hist_sum,json=histSum,proto3" json:"hist_sum,omitempty"`
	HistCount           uint64                 `protobuf:"varint,13,opt,name=hist_count,json=histCount,proto3" json:"hist_count,omitempty"`
	HistBuckets         []float64              `protobuf:"fixed64,14,rep,packed,name=hist_buckets,json=histBuckets,proto3" json:"hist_buckets,omitempty"`
	HistCounts          []uint64               `protobuf:"varint,15,rep,packed,name=hist_counts,json=histCounts,proto3" json:"hist_counts,omitempty"`
	Attributes          map[string]string      `protobuf:"bytes,16,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_metric_row_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_metric_row_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_metric_row_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetTeamId() uint32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Row) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Row) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Row) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *Row) GetTemporality() string {
	if x != nil {
		return x.Temporality
	}
	return ""
}

func (x *Row) GetIsMonotonic() bool {
	if x != nil {
		return x.IsMonotonic
	}
	return false
}

func (x *Row) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Row) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Row) GetResourceFingerprint() string {
	if x != nil {
		return x.ResourceFingerprint
	}
	return ""
}

func (x *Row) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Row) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Row) GetHistSum() float64 {
	if x != nil {
		return x.HistSum
	}
	return 0
}

func (x *Row) GetHistCount() uint64 {
	if x != nil {
		return x.HistCount
	}
	return 0
}

func (x *Row) GetHistBuckets() []float64 {
	if x != nil {
		return x.HistBuckets
	}
	return nil
}

func (x *Row) GetHistCounts() []uint64 {
	if x != nil {
		return x.HistCounts
	}
	return nil
}

func (x *Row) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_metric_row_proto protoreflect.FileDescriptor

const file_metric_row_proto_rawDesc = "" +
	"\n" +
	"\x10metric_row.proto\x12\x18optikk.ingest.metrics.v1\"\xe5\x04\n" +
	"\x03Row\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\rR\x06teamId\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x1f\n" +
	"\vmetric_type\x18\x04 \x01(\tR\n" +
	"metricType\x12 \n" +
	"\vtemporality\x18\x05 \x01(\tR\vtemporality\x12!\n" +
	"\fis_monotonic\x18\x06 \x01(\bR\visMonotonic\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x121\n" +
	"\x14resource_fingerprint\x18\t \x01(\tR\x13resourceFingerprint\x12!\n" +
	"\ftimestamp_ns\x18\n" +
	" \x01(\x03R\vtimestampNs\x12\x14\n" +
	"\x05value\x18\v \x01(\x01R\x05value\x12\x19\n" +
	"\bhist_sum\x18\f \x01(\x01R\ahistSum\x12\x1d\n" +
	"\n" +
	"hist_count\x18\r \x01(\x04R\thistCount\x12!\n" +
	"\fhist_buckets\x18\x0e \x03(\x01R\vhistBuckets\x12\x1f\n" +
	"\vhist_counts\x18\x0f \x03(\x04R\n" +
	"histCounts\x12M\n" +
	"\n" +
	"attributes\x18\x10 \x03(\v2-.optikk.ingest.metrics.v1.Row.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BOZMgithub.com/Optikk-Org/optikk-backend/internal/ingestion/metrics/schema;schemab\x06proto3"

var (
	file_metric_row_proto_rawDescOnce sync.Once
	file_metric_row_proto_rawDescData []byte
)

func file_metric_row_proto_rawDescGZIP() []byte {
	file_metric_row_proto_rawDescOnce.Do(func() {
		file_metric_row_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metric_row_proto_rawDesc), len(file_metric_row_proto_rawDesc)))
	})
	return file_metric_row_proto_rawDescData
}

var file_metric_row_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metric_row_proto_goTypes = []any{
	(*Row)(nil), // 0: optikk.ingest.metrics.v1.Row
	nil,         // 1: optikk.ingest.metrics.v1.Row.AttributesEntry
}
var file_metric_row_proto_depIdxs = []int32{
	1, // 0: optikk.ingest.metrics.v1.Row.attributes:type_name -> optikk.ingest.metrics.v1.Row.AttributesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metric_row_proto_init() }
func file_metric_row_proto_init() {
	if File_metric_row_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metric_row_proto_rawDesc), len(file_metric_row_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metric_row_proto_goTypes,
		DependencyIndexes: file_metric_row_proto_depIdxs,
		MessageInfos:      file_metric_row_proto_msgTypes,
	}.Build()
	File_metric_row_proto = out.File
	file_metric_row_proto_goTypes = nil
	file_metric_row_proto_depIdxs = nil
}
