package service

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func deploymentsTab() dashboardcfg.TabDefinition {
	serviceNameParam := dashboardcfg.MustQueryParams(map[string]any{
		"serviceName": "{serviceName}",
	})
	return dashboardcfg.TabDefinition{
		ID:     "deployments",
		PageID: "service",
		Label:  "Deployments",
		Order:  10,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "deployment-status", Title: "Deployment Status", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "version-traffic", Title: "Version Traffic Over Time", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("stacked")},
			dashboardcfg.SectionDefinition{ID: "deployment-impact", Title: "Deployment Impact", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
			dashboardcfg.SectionDefinition{ID: "deployment-history", Title: "Deployment History", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "active-version",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "deployment-status",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/deployments/list", Params: serviceNameParam},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Active Version",
				Description:   "Most recent service.version on spans for this service in the selected time range.",
				TitleIcon:     "Tag",
				ValueField:    "active_version",
			},
			dashboardcfg.PanelDefinition{
				ID:            "deployment-count",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "deployment-status",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/deployments/list", Params: serviceNameParam},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Deployment Count",
				Description:   "Distinct (version × environment) pairs observed in the range.",
				TitleIcon:     "Layers",
				ValueField:    "total",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "version-traffic-chart",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("wide-chart"),
				SectionID:     "version-traffic",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/deployments/timeline", Params: serviceNameParam},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Request rate by version",
				Description:   "Root-span request rate over time, one series per service.version. Shifts indicate rollouts.",
				TitleIcon:     "TrendingUp",
				GroupByKey:    "version",
				ValueKey:      "rps",
			},
			dashboardcfg.PanelDefinition{
				ID:            "deployment-impact-table",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("detail-table"),
				SectionID:     "deployment-impact",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/deployments/impact", Params: serviceNameParam},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Impact vs previous version",
				Description:   "Before/after windows: before = previous deployment interval; after = this version until the next (or end of range). First row is baseline (no delta).",
				TitleIcon:     "GitCompare",
				DataKey:       "impacts",
				Columns: []dashboardcfg.DashboardTableColumn{
					{Key: "version", Label: "Version", Align: dashboardcfg.ColumnAlign("left")},
					{Key: "environment", Label: "Environment", Align: dashboardcfg.ColumnAlign("left")},
					{Key: "is_baseline", Label: "Baseline", Align: dashboardcfg.ColumnAlign("center"), Width: dashboardcfg.IntPtr(90)},
					{Key: "error_rate_before", Label: "Err % before", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(110)},
					{Key: "error_rate_after", Label: "Err % after", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(110)},
					{Key: "error_rate_delta", Label: "Err Δ", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(90)},
					{Key: "p95_before", Label: "p95 ms before", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
					{Key: "p95_after", Label: "p95 ms after", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
					{Key: "p95_delta", Label: "p95 Δ", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(90)},
				},
			},
			dashboardcfg.PanelDefinition{
				ID:            "deployment-history-table",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("detail-table"),
				SectionID:     "deployment-history",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/deployments/list", Params: serviceNameParam},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Deployments",
				Description:   "Distinct versions with first/last seen span timestamps in the selected window.",
				TitleIcon:     "Table",
				DataKey:       "deployments",
				Columns: []dashboardcfg.DashboardTableColumn{
					{Key: "version", Label: "Version", Align: dashboardcfg.ColumnAlign("left")},
					{Key: "environment", Label: "Environment", Align: dashboardcfg.ColumnAlign("left")},
					{Key: "first_seen", Label: "First seen", Align: dashboardcfg.ColumnAlign("left")},
					{Key: "last_seen", Label: "Last seen", Align: dashboardcfg.ColumnAlign("left")},
					{Key: "span_count", Label: "Spans", Align: dashboardcfg.ColumnAlign("right"), Formatter: "number", Width: dashboardcfg.IntPtr(100)},
					{Key: "is_active", Label: "Active", Align: dashboardcfg.ColumnAlign("center"), Width: dashboardcfg.IntPtr(80)},
				},
			},
		},
	}
}
