package overview

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/platform/dashboardcfg"
)

func apmTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "apm",
		PageID: "overview",
		Label:  "APM",
		Order:  30,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "apm-summary", Title: "Key Metrics", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "process-signals", Title: "Process Signals", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "resource-trends", Title: "Resource Trends", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			// ── Section: Key Metrics (kpi-band) ──
			dashboardcfg.PanelDefinition{
				ID:            "rpc-p95-duration",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "apm-summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/rpc-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "RPC p95 Duration",
				Description:   "Shows the 95th-percentile RPC call duration in milliseconds. An upward trend means most users are starting to feel latency, not just outlier requests.",
				TitleIcon:     "Clock",
				ValueField:    "p95",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "rpc-p99-duration",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "apm-summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/rpc-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "RPC p99 Duration",
				Description:   "Shows the 99th-percentile RPC call duration in milliseconds. This captures worst-case latency; sustained increases may indicate resource contention or GC pauses.",
				TitleIcon:     "Clock",
				ValueField:    "p99",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "rss-memory",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "apm-summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/process-memory", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "RSS Memory",
				Description:   "Shows the resident set size, representing physical memory actively used by the process. Steady growth without plateau may indicate a memory leak.",
				TitleIcon:     "HardDrive",
				ValueField:    "rss",
				Formatter:     "bytes",
			},
			dashboardcfg.PanelDefinition{
				ID:            "virtual-memory",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "apm-summary",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/process-memory", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Virtual Memory",
				Description:   "Shows total virtual address space reserved by the process. A large gap between virtual and RSS memory is normal, but runaway growth can exhaust address space limits.",
				TitleIcon:     "HardDrive",
				ValueField:    "vms",
				Formatter:     "bytes",
			},
			dashboardcfg.PanelDefinition{
				ID:            "apm-messaging-duration",
				PanelType:     dashboardcfg.PanelType("stat-summary"),
				LayoutVariant: dashboardcfg.LayoutVariant("wide-compact"),
				SectionID:     "apm-summary",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/messaging-publish-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Messaging Publish Duration p50/p95/p99",
				Description:   "Shows median, 95th, and 99th percentile durations for publishing messages to queues. Rising values suggest broker back-pressure or network congestion.",
				TitleIcon:     "Send",
			},

			// ── Section: Process Signals (two-up) ──
			// RPC throughput + CPU side-by-side: two views of the same process under load.
			dashboardcfg.PanelDefinition{
				ID:            "apm-rpc-request-rate",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "process-signals",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/rpc-request-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "RPC Request Rate",
				Description:   "Tracks RPC calls per second over time. Correlate traffic dips or spikes with deployment events or upstream changes to identify causation.",
				TitleIcon:     "Activity",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "apm-process-cpu",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "process-signals",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/process-cpu", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Process CPU Time by State",
				Description:   "Plots CPU time split by state (user, system) over time. A rising system-time share relative to user time may indicate excessive syscalls or context switching.",
				TitleIcon:     "Cpu",
				GroupByKey:    "state",
				ValueKey:      "value",
			},

			// ── Section: Resource Trends (two-up) ──
			// File descriptor health + uptime: process stability signals.
			dashboardcfg.PanelDefinition{
				ID:            "apm-open-fds",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "resource-trends",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/open-fds", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Open File Descriptors",
				Description:   "Tracks the number of open file descriptors over time. A steady upward trend without leveling off suggests descriptor leaks that may eventually hit OS limits.",
				TitleIcon:     "FileText",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "apm-uptime",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "resource-trends",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/apm/uptime", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Process Uptime",
				Description:   "Shows how long the process has been running since its last restart. Frequent resets indicate crash loops or aggressive restart policies.",
				TitleIcon:     "Clock",
				ValueKey:      "value",
			},
		},
	}
}
