package infrastructure

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func resourceUtilizationTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "resource-utilization",
		PageID: "infrastructure",
		Label:  "Resource Utilization",
		Order:  10,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "summary", Title: "Key Metrics", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "trends", Title: "Golden Signals", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "details", Title: "Details", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "avg-cpu",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/resource-utilisation/avg-cpu", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg CPU",
				Description:   "Shows the average CPU utilization across all hosts. Look for sustained values above 80% that may indicate capacity pressure.",
				TitleIcon:     "Cpu",
				ValueField:    "value",
				Formatter:     "percent1",
			},
			dashboardcfg.PanelDefinition{
				ID:            "avg-memory",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/resource-utilisation/avg-memory", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg Memory",
				Description:   "Shows the average memory utilization across all hosts. Watch for values approaching 90% which may lead to OOM conditions.",
				TitleIcon:     "HardDrive",
				ValueField:    "value",
				Formatter:     "percent1",
			},
			dashboardcfg.PanelDefinition{
				ID:            "avg-network",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/resource-utilisation/avg-network", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg Network",
				Description:   "Shows the average network bandwidth utilization across all hosts. Spikes may correlate with increased traffic or data-intensive workloads.",
				TitleIcon:     "Network",
				ValueField:    "value",
				Formatter:     "percent1",
			},
			dashboardcfg.PanelDefinition{
				ID:            "avg-conn-pool",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/resource-utilisation/avg-conn-pool", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg Conn Pool",
				Description:   "Shows the average connection pool utilization across database connections. High values indicate potential connection exhaustion.",
				TitleIcon:     "Database",
				ValueField:    "value",
				Formatter:     "percent1",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-load-average",
				PanelType:     dashboardcfg.PanelType("stat-summary"),
				LayoutVariant: dashboardcfg.LayoutVariant("wide-compact"),
				SectionID:     "summary",
				Order:         120,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/cpu/load-average", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Load Average (1m / 5m / 15m)",
				Description:   "Shows the 1-minute, 5-minute, and 15-minute host load averages. Values exceeding the CPU core count suggest saturation.",
				TitleIcon:     "Activity",
				Formatter:     "number",
				SummaryFields: []dashboardcfg.StatSummaryField{
					dashboardcfg.StatSummaryField{Label: "1m", Field: "load_1m"},
					dashboardcfg.StatSummaryField{Label: "5m", Field: "load_5m"},
					dashboardcfg.StatSummaryField{Label: "15m", Field: "load_15m"},
				},
			},
			dashboardcfg.PanelDefinition{
				ID:            "cpu-usage",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/cpu/usage-percentage", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "CPU Usage Percentage",
				Description:   "Tracks host-level CPU usage over time broken down by pod. Look for upward trends or periodic spikes that align with workload patterns.",
				TitleIcon:     "Cpu",
				GroupByKey:    "pod",
				ValueKey:      "value",
				DatasetLabel:  "CPU Util",
			},
			dashboardcfg.PanelDefinition{
				ID:            "memory-usage",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         60,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/memory/usage-percentage", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Memory Usage Percentage",
				Description:   "Tracks host-level memory usage over time broken down by pod. A steady upward climb may indicate a memory leak.",
				TitleIcon:     "HardDrive",
				GroupByKey:    "pod",
				ValueKey:      "value",
				DatasetLabel:  "Mem Util",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-cpu-time",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         90,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/cpu/time", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "CPU Time by State",
				Description:   "Shows CPU time split across states such as user, system, and iowait. High iowait signals disk or network bottlenecks.",
				TitleIcon:     "Cpu",
				GroupByKey:    "state",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-memory-usage",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         100,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/memory/usage", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Memory Usage by State",
				Description:   "Shows host memory broken down by state such as used, cached, and buffered. Watch for shrinking free memory over time.",
				TitleIcon:     "HardDrive",
				GroupByKey:    "state",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-swap-usage",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         110,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/memory/swap", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Swap Usage by State",
				Description:   "Tracks swap memory usage over time. Any significant swap activity indicates memory pressure on the host.",
				TitleIcon:     "HardDrive",
				GroupByKey:    "state",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-disk-io",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         130,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/disk/io", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Disk I/O (Read / Write)",
				Description:   "Tracks disk read and write throughput in bytes over time. Sudden spikes may indicate heavy logging or database flushes.",
				TitleIcon:     "HardDrive",
				GroupByKey:    "direction",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-disk-operations",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         140,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/disk/operations", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Disk Operations (Read / Write)",
				Description:   "Tracks the number of disk read and write IOPS over time. High operation counts with low throughput suggest small random I/O.",
				TitleIcon:     "HardDrive",
				GroupByKey:    "direction",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-disk-io-time",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         150,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/disk/io-time", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Disk I/O Time",
				Description:   "Shows the cumulative time the disk spent on I/O operations. Rising values indicate increasing disk latency on the host.",
				TitleIcon:     "Clock",
				GroupByKey:    "pod",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-filesystem-usage",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         160,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/disk/filesystem-usage", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Filesystem Usage by Mountpoint",
				Description:   "Shows disk space consumed per filesystem mountpoint. Watch for mountpoints approaching capacity to prevent write failures.",
				TitleIcon:     "FolderOpen",
				GroupByKey:    "mountpoint",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-filesystem-util",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         170,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/disk/filesystem-utilization", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Filesystem Utilization",
				Description:   "Tracks the percentage of disk capacity in use across hosts. Values above 85% warrant immediate attention.",
				TitleIcon:     "FolderOpen",
				GroupByKey:    "pod",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-network-io",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         180,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/network/io", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Network I/O (Transmit / Receive)",
				Description:   "Shows network throughput split by transmit and receive directions. Look for asymmetric patterns that may indicate unusual traffic flows.",
				TitleIcon:     "Network",
				GroupByKey:    "direction",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-network-packets",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         190,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/network/packets", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Network Packets (Transmit / Receive)",
				Description:   "Tracks the packet rate for transmitted and received traffic. High packet rates with low throughput suggest many small requests.",
				TitleIcon:     "Network",
				GroupByKey:    "direction",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-network-errors",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         200,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/network/errors", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Network Errors by State",
				Description:   "Shows network-level office categorized by state. Any non-zero values warrant investigation into host NIC or network issues.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "state",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-network-dropped",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         210,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/network/dropped", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Dropped Packets",
				Description:   "Tracks the number of packets dropped at the host network interface. Dropped packets often indicate buffer exhaustion or rate limiting.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "pod",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-process-count",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         220,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/cpu/process-count", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Process Count by Status",
				Description:   "Shows the number of host processes grouped by status such as running, sleeping, or blocked. A rising blocked count signals resource contention.",
				TitleIcon:     "Activity",
				GroupByKey:    "state",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "infra-network-connections",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         230,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/network/connections", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Network Connections by State",
				Description:   "Tracks TCP connections by state such as established, time_wait, and close_wait. A buildup of time_wait connections may indicate connection churn.",
				TitleIcon:     "Network",
				GroupByKey:    "state",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "by-service",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "details",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/resource-utilisation/by-service", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Resource Usage by Service",
				Description:   "Breaks down CPU, memory, and network consumption per service. Identify which services are the heaviest resource consumers.",
				TitleIcon:     "Layers",
			},
			dashboardcfg.PanelDefinition{
				ID:            "by-instance",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "details",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/resource-utilisation/by-instance", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Resource Usage by Instance",
				Description:   "Breaks down CPU, memory, and network consumption per host instance. Use this to spot hot instances that need rebalancing.",
				TitleIcon:     "Server",
			},
		},
	}
}
