package overview

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func summaryTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "summary",
		PageID: "overview",
		Label:  "Summary",
		Order:  10,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "overview-stats", Title: "Key Metrics", Order: 5, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("three-up")},
			dashboardcfg.SectionDefinition{ID: "golden-signals", Title: "Golden Signals", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "red-metrics", Title: "RED Metrics", Order: 15, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "service-health", Title: "Service Health", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("summary-plus-health")},
			dashboardcfg.SectionDefinition{ID: "quality-signals", Title: "Quality Signals", Order: 25, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "top-consumers", Title: "Top Consumers", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			// ── Section: Key Metrics (overview-stats) ──
			dashboardcfg.PanelDefinition{
				ID:            "overview-stat-cards",
				PanelType:     dashboardcfg.PanelType("stat-cards-grid"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "overview-stats",
				Order:         1,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Overview Stats",
				Description:   "High-level KPIs across all services including request rate, error rate, and latency. Use this as a quick health check for your entire system.",
				TitleIcon:     "BarChart3",
			},
			dashboardcfg.PanelDefinition{
				ID:            "slo-indicators",
				PanelType:     dashboardcfg.PanelType("slo-indicators"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "overview-stats",
				Order:         2,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/services", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "SLO Indicators",
				Description:   "Visual indicators showing whether each service is meeting its Service Level Objectives. Green means within target; red signals SLO breach.",
				TitleIcon:     "ShieldCheck",
			},
			dashboardcfg.PanelDefinition{
				ID:            "service-health-grid",
				PanelType:     dashboardcfg.PanelType("service-health-grid"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "overview-stats",
				Order:         3,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/services", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Services Overview",
				Description:   "Grid of all reporting services with health indicators. Click any service to drill down into its detail page.",
				TitleIcon:     "Server",
			},

			// ── Section: Golden Signals ──
			dashboardcfg.PanelDefinition{
				ID:            "red-request-rate",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "golden-signals",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/request-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Request Rate by Service",
				Description:   "Requests per second over time, grouped by service. Watch for sudden spikes that may indicate retry storms or traffic shifts between services.",
				TitleIcon:     "TrendingUp",
				GroupByKey:    "service_name",
				ValueKey:      "rps",
			},
			dashboardcfg.PanelDefinition{
				ID:            "red-error-rate",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "golden-signals",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/error-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Error Rate by Service",
				Description:   "Tracks error percentage over time for each service. Diverging lines help isolate which service is the source of a reliability regression.",
				TitleIcon:     "AlertCircle",
				GroupByKey:    "service_name",
				ValueKey:      "error_pct",
			},
			dashboardcfg.PanelDefinition{
				ID:            "p95-latency",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "golden-signals",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/p95-latency", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "p95 Latency",
				Description:   "95th-percentile response time over time per service. Catches tail-latency regressions that averages would hide.",
				TitleIcon:     "Clock",
				GroupByKey:    "service_name",
				ValueKey:      "p95",
			},

			// ── Section: RED Metrics (KPI band) ──
			dashboardcfg.PanelDefinition{
				ID:            "stat-service-count",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "red-metrics",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Services",
				Description:   "Shows the total number of distinct services reporting spans in the selected time range. A sudden drop may indicate instrumentation gaps or service outages.",
				TitleIcon:     "Layers",
				ValueField:    "service_count",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-total-rps",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "red-metrics",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Total RPS",
				Description:   "Shows the aggregate requests per second across all services. A rising value indicates increased traffic; a sudden drop may signal an upstream failure or routing change.",
				TitleIcon:     "TrendingUp",
				ValueField:    "total_rps",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-avg-error-pct",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "red-metrics",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg Error Rate",
				Description:   "Shows the mean error percentage averaged across all services. An increase signals degraded reliability and warrants drilling into per-service error rates.",
				TitleIcon:     "AlertCircle",
				ValueField:    "avg_error_pct",
				Formatter:     "percent2",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-avg-p95",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "red-metrics",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg p95 Latency",
				Description:   "Shows the average 95th-percentile latency across all services in milliseconds. Rising values indicate that tail latency is worsening fleet-wide.",
				TitleIcon:     "Clock",
				ValueField:    "avg_p95_ms",
				Formatter:     "ms",
			},

			// ── Section: Service Health ──
			dashboardcfg.PanelDefinition{
				ID:            "apdex-scores",
				PanelType:     dashboardcfg.PanelType("gauge"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "service-health",
				Order:         50,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/apdex", Params: dashboardcfg.MustQueryParams(map[string]any{
					"satisfied_ms":  300,
					"tolerating_ms": 1200,
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Apdex Score by Service",
				Description: "Application Performance Index scored 0 to 1, where 1.0 means all requests completed within the satisfied threshold (300 ms). Below 0.7 is generally considered poor.",
				TitleIcon:   "Target",
				GroupByKey:  "service_name",
				ValueKey:    "apdex",
			},

			// ── Section: Quality Signals ──
			dashboardcfg.PanelDefinition{
				ID:            "span-kind-breakdown",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "quality-signals",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/span-kind-breakdown", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Throughput by Span Kind",
				Description:   "Shows span volume over time grouped by kind (SERVER, CLIENT, INTERNAL, etc.). Useful for understanding whether traffic growth originates from inbound requests or internal fan-out.",
				TitleIcon:     "GitBranch",
				GroupByKey:    "kind_string",
				ValueKey:      "span_count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "errors-by-route",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("wide-chart"),
				SectionID:     "quality-signals",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/errors-by-route", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Errors by HTTP Route",
				Description:   "Ranks HTTP routes by total error count to surface the noisiest endpoints. Use this to prioritize which routes need immediate attention.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "http_route",
				ValueKey:      "error_count",
			},

			// ── Section: Top Consumers ──
			dashboardcfg.PanelDefinition{
				ID:            "services-table",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "top-consumers",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/services", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Services",
				Description:   "All services reporting in the selected time window with key metrics including request rate, error rate, and p95 latency.",
				TitleIcon:     "Layers",
			},
			dashboardcfg.PanelDefinition{
				ID:            "endpoints-table",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "top-consumers",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/top-endpoints", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Top Endpoints",
				Description:   "Highest-traffic endpoints ranked by request volume. Helps identify which endpoints drive the most load.",
				TitleIcon:     "List",
			},
		},
	}
}
