package overview

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func redMetricsTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "red-metrics",
		PageID: "overview",
		Label:  "RED Metrics",
		Order:  10,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "g1", Title: "Overview", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "g2", Title: "Rate, Error & Latency", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g3", Title: "Quality Signals", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "g4", Title: "Top Offenders", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "stat-service-count",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "g1",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Services",
				Description:   "Shows the total number of distinct services reporting spans in the selected time range. A sudden drop may indicate instrumentation gaps or service outages.",
				TitleIcon:     "Layers",
				ValueField:    "service_count",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-total-rps",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "g1",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Total RPS",
				Description:   "Shows the aggregate requests per second across all services. A rising value indicates increased traffic; a sudden drop may signal an upstream failure or routing change.",
				TitleIcon:     "TrendingUp",
				ValueField:    "total_rps",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-avg-error-pct",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "g1",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg Error Rate",
				Description:   "Shows the mean error percentage averaged across all services. An increase signals degraded reliability and warrants drilling into per-service error rates.",
				TitleIcon:     "AlertCircle",
				ValueField:    "avg_error_pct",
				Formatter:     "percent2",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-avg-p95",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "g1",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg p95 Latency",
				Description:   "Shows the average 95th-percentile latency across all services in milliseconds. Rising values indicate that tail latency is worsening fleet-wide.",
				TitleIcon:     "Clock",
				ValueField:    "avg_p95_ms",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "request-rate",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g2",
				Order:         60,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/request-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Request Rate by Service",
				Description:   "Plots requests per second over time, grouped by service. Watch for sudden spikes that may indicate retry storms or traffic shifts between services.",
				TitleIcon:     "TrendingUp",
				GroupByKey:    "service_name",
				ValueKey:      "rps",
			},
			dashboardcfg.PanelDefinition{
				ID:            "error-rate",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g2",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/error-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Error Rate by Service",
				Description:   "Tracks error percentage over time for each service. Diverging lines help isolate which service is the source of a reliability regression.",
				TitleIcon:     "AlertCircle",
				GroupByKey:    "service_name",
				ValueKey:      "error_pct",
			},
			dashboardcfg.PanelDefinition{
				ID:            "span-kind-breakdown",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "g2",
				Order:         90,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/span-kind-breakdown", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Throughput by Span Kind",
				Description:   "Shows span volume over time grouped by kind (SERVER, CLIENT, INTERNAL, etc.). Useful for understanding whether traffic growth originates from inbound requests or internal fan-out.",
				TitleIcon:     "GitBranch",
				GroupByKey:    "kind_string",
				ValueKey:      "span_count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "errors-by-route",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("wide-chart"),
				SectionID:     "g3",
				Order:         120,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/errors-by-route", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Errors by HTTP Route",
				Description:   "Ranks HTTP routes by total error count to surface the noisiest endpoints. Use this to prioritize which routes need immediate attention.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "http_route",
				ValueKey:      "error_count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "top-slow-operations",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "g4",
				Order:         130,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/top-slow-operations", Params: dashboardcfg.MustQueryParams(map[string]any{
					"limit": 20,
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Top Slowest Operations (p99)",
				Description: "Lists operations ranked by 99th-percentile duration, showing the worst tail-latency offenders. Focus optimization efforts on the top entries for maximum user-impact improvement.",
				TitleIcon:   "TrendingDown",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "operation_name", Label: "Operation Name", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
				},
			},
			dashboardcfg.PanelDefinition{
				ID:            "top-error-operations",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "g4",
				Order:         140,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/top-error-operations", Params: dashboardcfg.MustQueryParams(map[string]any{
					"limit": 20,
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Top Error Operations",
				Description: "Lists operations ranked by error rate descending. Rows at the top represent the most unreliable operations and are prime candidates for bug fixes or retry tuning.",
				TitleIcon:   "AlertTriangle",
			},
		},
	}
}
