package overview

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func httpTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "http",
		PageID: "overview",
		Label:  "HTTP",
		Order:  20,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "server-summary", Title: "Server Overview", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("three-up")},
			dashboardcfg.SectionDefinition{ID: "server-trends", Title: "Server Traffic", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "route-breakdown", Title: "Route-Level Breakdown", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("chart-grid-plus-details")},
			dashboardcfg.SectionDefinition{ID: "error-analysis", Title: "Error Analysis", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("chart-grid-plus-details")},
			dashboardcfg.SectionDefinition{ID: "outbound-summary", Title: "Outbound / External HTTP Summary", Order: 50, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "outbound-breakdowns", Title: "Outbound / External HTTP", Order: 60, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			// ── Section: Server Overview ──
			dashboardcfg.PanelDefinition{
				ID:            "http-request-duration",
				PanelType:     dashboardcfg.PanelType("stat-summary"),
				LayoutVariant: dashboardcfg.LayoutVariant("compact"),
				SectionID:     "server-summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/request-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Server Request Duration p50/p95/p99",
				Description:   "Shows median, 95th, and 99th percentile server-side request durations. Rising percentiles indicate backend processing slowdowns that may degrade user experience.",
				TitleIcon:     "Clock",
			},
			dashboardcfg.PanelDefinition{
				ID:            "http-request-body-size",
				PanelType:     dashboardcfg.PanelType("stat-summary"),
				LayoutVariant: dashboardcfg.LayoutVariant("compact"),
				SectionID:     "server-summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/request-body-size", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Request Body Size p50/p95/p99",
				Description:   "Shows median, 95th, and 99th percentile inbound request payload sizes. Unexpectedly large payloads can increase serialization cost and memory pressure.",
				TitleIcon:     "Upload",
				Formatter:     "bytes",
			},
			dashboardcfg.PanelDefinition{
				ID:            "http-response-body-size",
				PanelType:     dashboardcfg.PanelType("stat-summary"),
				LayoutVariant: dashboardcfg.LayoutVariant("compact"),
				SectionID:     "server-summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/response-body-size", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Response Body Size p50/p95/p99",
				Description:   "Shows median, 95th, and 99th percentile outbound response payload sizes. Growing response sizes can increase network egress cost and client rendering time.",
				TitleIcon:     "Download",
				Formatter:     "bytes",
			},

			// ── Section: Server Traffic ──
			dashboardcfg.PanelDefinition{
				ID:            "http-request-rate",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "server-trends",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/request-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "HTTP Request Rate by Status Code",
				Description:   "Plots inbound request rate over time, split by HTTP status code. Watch for growing non-2xx lines that diverge from the success baseline.",
				TitleIcon:     "Globe",
				GroupByKey:    "status_code",
				ValueKey:      "count",
			},

			// ── Section: Route-Level Breakdown ──
			// Chart first — gives context before the detail tables below.
			dashboardcfg.PanelDefinition{
				ID:            "route-error-timeseries",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "route-breakdown",
				Order:         5,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/routes/error-timeseries", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Route Error Rate Over Time",
				Description:   "Plots per-route error counts over time to reveal which routes are contributing to error spikes. Diverging lines help isolate the offending endpoint.",
				TitleIcon:     "TrendingDown",
				GroupByKey:    "http_route",
				ValueKey:      "error_count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "top-routes-volume",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "route-breakdown",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/routes/top-by-volume", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Top Routes by Request Volume",
				Description:   "Ranks HTTP routes by total request count to highlight the busiest endpoints. Use this to identify hot paths that benefit most from optimization.",
				TitleIcon:     "BarChart2",
				GroupByKey:    "route",
				ValueKey:      "req_count",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "route", Label: "Route", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(260)},
					dashboardcfg.DashboardTableColumn{Key: "req_count", Label: "Request Count", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
				},
			},
			dashboardcfg.PanelDefinition{
				ID:            "top-routes-latency",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "route-breakdown",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/routes/top-by-latency", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Top Routes by p95 Latency",
				Description:   "Ranks HTTP routes by their 95th-percentile response time. Routes at the top are the slowest and may need query optimization or caching.",
				TitleIcon:     "Clock",
				GroupByKey:    "route",
				ValueKey:      "p95_ms",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "route", Label: "Route", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(260)},
					dashboardcfg.DashboardTableColumn{Key: "p95_ms", Label: "P95 Latency", Formatter: "ms", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
				},
			},
			dashboardcfg.PanelDefinition{
				ID:            "route-error-rate",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "route-breakdown",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/routes/error-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Error Rate by Route",
				Description:   "Compares error percentages across HTTP routes. Routes with elevated error rates relative to peers signal localized reliability problems.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "route",
				ValueKey:      "error_pct",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "route", Label: "Route", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(260)},
					dashboardcfg.DashboardTableColumn{Key: "error_pct", Label: "Error %", Formatter: "percent1", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
				},
			},

			// ── Section: Error Analysis (merged status-overview + status-errors) ──
			// Status distribution pie gives immediate visual context; tables + timeseries follow.
			dashboardcfg.PanelDefinition{
				ID:            "status-distribution",
				PanelType:     dashboardcfg.PanelType("pie"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "error-analysis",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/status-distribution", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "HTTP Status Distribution",
				Description:   "Compares the share of 2xx, 3xx, 4xx, and 5xx responses as a proportion of total traffic. A healthy distribution is dominated by the 2xx segment.",
				TitleIcon:     "PieChart",
				GroupByKey:    "status_group",
				ValueKey:      "count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "http-error-timeseries",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "error-analysis",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/error-timeseries", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Overall HTTP Error Rate Over Time",
				Description:   "Plots the aggregate HTTP error rate as a time series. Spikes that correlate with deployments or traffic changes help pinpoint the root cause of failures.",
				TitleIcon:     "AlertCircle",
				ValueKey:      "error_rate",
			},
			dashboardcfg.PanelDefinition{
				ID:            "http-5xx-by-route",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("detail-table"),
				SectionID:     "error-analysis",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/http-5xx-by-route", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "5xx Errors by Route & Service",
				Description:   "Lists each route-service pair with its 5xx error count, sorted by volume. Rows near the top are the highest-impact targets for reliability fixes.",
				TitleIcon:     "XCircle",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "http_route", Label: "HTTP Route", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(260)},
				},
			},

			// ── Section: Outbound / External HTTP Summary ──
			dashboardcfg.PanelDefinition{
				ID:            "http-client-duration",
				PanelType:     dashboardcfg.PanelType("stat-summary"),
				LayoutVariant: dashboardcfg.LayoutVariant("compact"),
				SectionID:     "outbound-summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/client-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Outbound HTTP Duration p50/p95/p99",
				Description:   "Shows median, 95th, and 99th percentile durations for outbound HTTP calls. A widening gap between p50 and p99 signals growing tail-latency variance in external dependencies.",
				TitleIcon:     "ArrowUpRight",
			},
			dashboardcfg.PanelDefinition{
				ID:            "dns-tls-duration",
				PanelType:     dashboardcfg.PanelType("stat-summary"),
				LayoutVariant: dashboardcfg.LayoutVariant("compact"),
				SectionID:     "outbound-summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/dns-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "DNS Lookup & TLS Handshake Duration",
				Description:   "Shows time spent on DNS resolution and TLS handshakes for outbound calls. Elevated values may point to DNS infrastructure issues or certificate negotiation overhead.",
				TitleIcon:     "Shield",
			},

			// ── Section: Outbound / External HTTP ──
			dashboardcfg.PanelDefinition{
				ID:            "external-top-hosts",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "outbound-breakdowns",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/external/top-hosts", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Top External Hosts by Volume",
				Description:   "Ranks external hosts by outbound request count. Dominance by a single host may indicate tight coupling or a candidate for caching.",
				TitleIcon:     "Globe",
				GroupByKey:    "host",
				ValueKey:      "req_count",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "host", Label: "Host", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(260)},
					dashboardcfg.DashboardTableColumn{Key: "req_count", Label: "Request Count", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
				},
			},
			dashboardcfg.PanelDefinition{
				ID:            "external-host-latency",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "outbound-breakdowns",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/external/host-latency", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "External Host p95 Latency",
				Description:   "Compares 95th-percentile response time across external hosts. Hosts with disproportionately high latency may be bottlenecking end-to-end request flow.",
				TitleIcon:     "Clock",
				GroupByKey:    "host",
				ValueKey:      "p95_ms",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "host", Label: "Host", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(260)},
					dashboardcfg.DashboardTableColumn{Key: "p95_ms", Label: "P95 Latency", Formatter: "ms", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
				},
			},
			dashboardcfg.PanelDefinition{
				ID:            "external-error-rate",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "outbound-breakdowns",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/http/external/error-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "External Host Error Rate",
				Description:   "Compares error percentages across external hosts. A host with a disproportionately high error rate may need circuit-breaking or fallback logic.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "host",
				ValueKey:      "error_pct",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "host", Label: "Host", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(260)},
					dashboardcfg.DashboardTableColumn{Key: "error_pct", Label: "Error %", Formatter: "percent1", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
				},
			},
		},
	}
}
