package overview

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func latencyAnalysisTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "latency-analysis",
		PageID: "overview",
		Label:  "Latency Analysis",
		Order:  40,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "summary", Title: "Latency Overview", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "trends", Title: "Latency Trends", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "distribution", Title: "Distribution Analysis", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "offenders", Title: "Top Offenders", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "stat-p50",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "P50 Latency",
				Description:   "Median request latency across all services. This is the latency most users experience under normal conditions.",
				TitleIcon:     "Clock",
				ValueField:    "avg_p50_ms",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-p99",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "P99 Latency",
				Description:   "99th-percentile latency. This captures worst-case tail latency; sustained increases may indicate resource contention or GC pauses.",
				TitleIcon:     "AlertCircle",
				ValueField:    "avg_p99_ms",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "stat-total-spans",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Total Spans",
				Description:   "Total number of spans analyzed in the selected time window. Provides context for the statistical significance of the percentile values.",
				TitleIcon:     "Layers",
				ValueField:    "total_span_count",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "p95-latency-timeseries",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/p95-latency", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "P95 Latency by Service",
				Description:   "Plots 95th-percentile latency over time grouped by service. Diverging lines help isolate which service is the source of a latency regression.",
				TitleIcon:     "TrendingUp",
				GroupByKey:    "service_name",
				ValueKey:      "p95_ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "histogram",
				PanelType:     dashboardcfg.PanelType("bar"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/latency/histogram", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Latency Distribution",
				Description:   "Shows the distribution of request durations across latency buckets. A long right tail indicates outlier requests that may disproportionately affect user experience.",
				TitleIcon:     "BarChart3",
				GroupByKey:    "bucket_label",
				LabelKey:      "bucket_label",
				ValueKey:      "span_count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "heatmap",
				PanelType:     dashboardcfg.PanelType("heatmap"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "distribution",
				Order:         10,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/latency/heatmap", Params: dashboardcfg.MustQueryParams(map[string]any{
					"interval": "5m",
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Latency Heatmap",
				Description: "Visualizes request latency over time with color intensity representing request density at each duration band. Hot bands shifting upward over time indicate progressive latency degradation.",
				TitleIcon:   "Activity",
				XKey:        "time_bucket",
				YKey:        "latency_bucket",
				ValueKey:    "span_count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "latency-breakdown",
				PanelType:     dashboardcfg.PanelType("bar"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "distribution",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/latency-breakdown", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Latency Budget by Service",
				Description:   "Shows total time spent in each service. Services consuming disproportionate latency budget are prime candidates for optimization.",
				TitleIcon:     "PieChart",
				GroupByKey:    "service_name",
				LabelKey:      "serviceName",
				ValueKey:      "totalMs",
			},
			dashboardcfg.PanelDefinition{
				ID:            "top-slow-operations",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "offenders",
				Order:         10,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/top-slow-operations", Params: dashboardcfg.MustQueryParams(map[string]any{
					"limit": 20,
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Top Slowest Operations (p99)",
				Description: "Lists operations ranked by 99th-percentile duration, showing the worst tail-latency offenders. Focus optimization efforts on the top entries for maximum user-impact improvement.",
				TitleIcon:   "TrendingDown",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "operation_name", Label: "Operation Name", Align: dashboardcfg.ColumnAlign("right"), Width: dashboardcfg.IntPtr(120)},
				},
			},
			dashboardcfg.PanelDefinition{
				ID:            "top-error-operations-latency",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "offenders",
				Order:         20,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/top-error-operations", Params: dashboardcfg.MustQueryParams(map[string]any{
					"limit": 20,
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Top Error Operations",
				Description: "Lists operations ranked by error rate. High error rates often correlate with latency spikes due to retries and fallback logic.",
				TitleIcon:   "AlertTriangle",
			},
		},
	}
}
