package overview

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func summaryTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "summary",
		PageID: "overview",
		Label:  "Summary",
		Order:  10,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "overview-stats", Title: "Key Metrics", Order: 5, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("three-up")},
			dashboardcfg.SectionDefinition{ID: "golden-signals", Title: "Golden Signals", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "service-health", Title: "Service Health", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("summary-plus-health")},
			dashboardcfg.SectionDefinition{ID: "top-consumers", Title: "Top Consumers", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "overview-stat-cards",
				PanelType:     dashboardcfg.PanelType("stat-cards-grid"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "overview-stats",
				Order:         1,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/services", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Overview Stats",
				Description:   "High-level KPIs across all services including request rate, error rate, and latency. Use this as a quick health check for your entire system.",
				TitleIcon:     "BarChart3",
			},
			dashboardcfg.PanelDefinition{
				ID:            "slo-indicators",
				PanelType:     dashboardcfg.PanelType("slo-indicators"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "overview-stats",
				Order:         2,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/services", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "SLO Indicators",
				Description:   "Visual indicators showing whether each service is meeting its Service Level Objectives. Green means within target; red signals SLO breach.",
				TitleIcon:     "ShieldCheck",
			},
			dashboardcfg.PanelDefinition{
				ID:            "service-health-grid",
				PanelType:     dashboardcfg.PanelType("service-health-grid"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "overview-stats",
				Order:         3,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/services", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Services Overview",
				Description:   "Grid of all reporting services with health indicators. Click any service to drill down into its detail page.",
				TitleIcon:     "Server",
			},
			dashboardcfg.PanelDefinition{
				ID:            "request-rate",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "golden-signals",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/request-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Request Rate",
				Description:   "Requests per second over time, broken down by service. Sudden drops may indicate an outage or traffic routing change.",
				TitleIcon:     "TrendingUp",
				GroupByKey:    "service_name",
			},
			dashboardcfg.PanelDefinition{
				ID:            "error-rate",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "golden-signals",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/error-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Error Rate",
				Description:   "Percentage of failed requests over time per service. Spikes often correlate with deployments or downstream failures.",
				TitleIcon:     "AlertCircle",
				GroupByKey:    "service_name",
			},
			dashboardcfg.PanelDefinition{
				ID:            "p95-latency",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "golden-signals",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/p95-latency", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "p95 Latency",
				Description:   "95th-percentile response time over time per service. Catches tail-latency regressions that averages would hide.",
				TitleIcon:     "Clock",
				GroupByKey:    "service_name",
				ValueKey:      "p95",
			},
			dashboardcfg.PanelDefinition{
				ID:            "apdex-scores",
				PanelType:     dashboardcfg.PanelType("gauge"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "service-health",
				Order:         50,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/red/apdex", Params: dashboardcfg.MustQueryParams(map[string]any{
					"satisfied_ms":  300,
					"tolerating_ms": 1200,
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Apdex Score by Service",
				Description: "Application Performance Index scored 0 to 1, where 1.0 means all requests completed within the satisfied threshold (300 ms). Below 0.7 is generally considered poor.",
				TitleIcon:   "Target",
				GroupByKey:  "service_name",
				ValueKey:    "apdex",
			},
			dashboardcfg.PanelDefinition{
				ID:            "error-hotspot-summary",
				PanelType:     dashboardcfg.PanelType("error-hotspot-ranking"),
				LayoutVariant: dashboardcfg.LayoutVariant("ranking"),
				SectionID:     "service-health",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/spans/error-hotspot", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Error Hotspot",
				Description:   "Ranked error hotspots by service and operation, ordered by error rate and error volume so the biggest failures surface first.",
				TitleIcon:     "Crosshair",
				XKey:          "operation_name",
				YKey:          "service_name",
				ValueKey:      "error_rate",
			},
			dashboardcfg.PanelDefinition{
				ID:            "services-table",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "top-consumers",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/services", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Services",
				Description:   "All services reporting in the selected time window with key metrics including request rate, error rate, and p95 latency.",
				TitleIcon:     "Layers",
			},
			dashboardcfg.PanelDefinition{
				ID:            "endpoints-table",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "top-consumers",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/overview/top-endpoints", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Top Endpoints",
				Description:   "Highest-traffic endpoints ranked by request volume. Helps identify which endpoints drive the most load.",
				TitleIcon:     "List",
			},
		},
	}
}
