CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  name VARCHAR(100) NOT NULL,
  avatar_url VARCHAR(255),
  role VARCHAR(20) NOT NULL DEFAULT 'member',
  teams JSON NOT NULL DEFAULT ('[]'),
  active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  INDEX idx_user_email (email)
);

CREATE TABLE IF NOT EXISTS teams (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  org_name VARCHAR(100),
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(50),
  description VARCHAR(500),
  active TINYINT(1) NOT NULL DEFAULT 1,
  color VARCHAR(50),
  icon VARCHAR(100),
  api_key VARCHAR(64) UNIQUE,
  retention_days INT NOT NULL DEFAULT 30,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  INDEX idx_team_org (organization_id),
  INDEX idx_team_slug (slug),
  INDEX idx_team_api_key (api_key)
);

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  team_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1000),
  type VARCHAR(20) NOT NULL,
  severity VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  service_name VARCHAR(100),
  condition_expr VARCHAR(500),
  metric VARCHAR(100),
  operator VARCHAR(20),
  threshold DOUBLE,
  duration_minutes INT,
  current_value DOUBLE,
  triggered_by VARCHAR(255),
  triggered_at DATETIME NULL,
  acknowledged_at DATETIME NULL,
  acknowledged_by VARCHAR(255),
  resolved_at DATETIME NULL,
  resolved_by VARCHAR(255),
  muted_until DATETIME NULL,
  mute_reason VARCHAR(500),
  runbook_url VARCHAR(2000),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  INDEX idx_alert_org (organization_id),
  INDEX idx_alert_team (team_id),
  INDEX idx_alert_status (status),
  INDEX idx_alert_severity (severity)
);

CREATE TABLE IF NOT EXISTS health_checks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  team_id BIGINT NOT NULL,
  organization_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  target_url VARCHAR(2000) NOT NULL,
  interval_seconds INT NOT NULL DEFAULT 60,
  timeout_ms INT NOT NULL DEFAULT 5000,
  expected_status INT DEFAULT 200,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  tags VARCHAR(1000),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  INDEX idx_hc_team (team_id),
  INDEX idx_hc_enabled (team_id, enabled)
);

CREATE TABLE IF NOT EXISTS health_check_results (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  team_id VARCHAR(36) NOT NULL,
  check_id VARCHAR(36) NOT NULL,
  check_name VARCHAR(255),
  check_type VARCHAR(50),
  target_url VARCHAR(2000),
  timestamp DATETIME NOT NULL,
  status VARCHAR(50),
  response_time_ms DOUBLE,
  http_status_code INT,
  error_message TEXT,
  region VARCHAR(100),
  INDEX idx_hcr_team (team_id, check_id, timestamp)
);
