package saturation

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func databaseTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "database",
		PageID: "saturation",
		Label:  "Database",
		Order:  10,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "summary", Title: "Key Metrics", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "trends", Title: "Golden Signals", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "details", Title: "Details", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("hero-plus-table")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "db-avg-latency-stat",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Avg Query Latency",
				Description:   "Shows the average latency across all database queries in the selected time range. A rising average often signals connection pool saturation or increasing query complexity.",
				TitleIcon:     "Clock",
				ValueField:    "avg_latency_ms",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-p95-latency-stat",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "p95 Query Latency",
				Description:   "Shows the 95th percentile database query latency. This represents the worst-case experience for most users and is more sensitive to slow queries than the average.",
				TitleIcon:     "Clock",
				ValueField:    "p95_latency_ms",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-p99-latency-stat",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "p99 Query Latency",
				Description:   "Shows the 99th percentile database query latency. Outlier queries captured here often point to missing indexes or lock contention.",
				TitleIcon:     "Activity",
				ValueField:    "p99_latency_ms",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-span-count-stat",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Total DB Spans",
				Description:   "Shows the total number of database spans observed in the selected time range. Use this to gauge overall database call volume.",
				TitleIcon:     "Database",
				ValueField:    "span_count",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-latency-by-system",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         60,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/latency/by-system", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "p99 Latency by System",
				Description:   "Tracks the 99th percentile query latency for each database system over time. Compare systems to identify which one contributes the most tail latency.",
				TitleIcon:     "Clock",
				GroupByKey:    "group_by",
				ValueKey:      "p99_ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-latency-by-operation",
				PanelType:     dashboardcfg.PanelType("latency"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/latency/by-operation", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "p99 Latency by Operation",
				Description:   "Tracks the 99th percentile query latency grouped by operation type (SELECT, INSERT, UPDATE, etc.). Watch for specific operations whose latency diverges from the baseline.",
				TitleIcon:     "Activity",
				GroupByKey:    "group_by",
				ValueKey:      "p99_ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-ops-by-system",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/ops/by-system", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Ops/sec by System",
				Description:   "Tracks the query throughput for each database system over time. Correlate throughput changes with latency shifts to distinguish load-driven slowdowns from efficiency regressions.",
				TitleIcon:     "BarChart",
				GroupByKey:    "group_by",
				ValueKey:      "ops_per_sec",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-ops-by-operation",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         90,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/ops/by-operation", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Ops/sec by Operation",
				Description:   "Tracks query throughput grouped by operation type over time. Helps identify unexpected spikes in write operations or unusual read patterns.",
				TitleIcon:     "BarChart",
				GroupByKey:    "group_by",
				ValueKey:      "ops_per_sec",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-read-vs-write",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         100,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/ops/read-vs-write", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Read vs Write Ops/sec",
				Description:   "Compares read and write operation throughput over time. Shifts in the read/write ratio can reveal caching issues or unexpected write amplification.",
				TitleIcon:     "GitPullRequest",
				ValueKey:      "read_ops_per_sec",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-errors-by-system",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         130,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/errors/by-system", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Errors/sec by System",
				Description:   "Tracks database error rates for each system over time. Spikes correlating with deployment events may indicate schema migration issues or incompatible queries.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "group_by",
				ValueKey:      "errors_per_sec",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-errors-by-type",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         140,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/errors/by-error-type", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Errors/sec by Error Type",
				Description:   "Tracks database error rates grouped by error type over time. Helps distinguish transient connection errors from persistent query failures.",
				TitleIcon:     "AlertCircle",
				GroupByKey:    "group_by",
				ValueKey:      "errors_per_sec",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-connection-count",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         150,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/connections/count", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Connection Count by State",
				Description:   "Tracks the number of database connections grouped by state (active, idle, waiting). A high ratio of waiting connections signals connection pool exhaustion.",
				TitleIcon:     "Network",
				GroupByKey:    "state",
				ValueKey:      "count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-connection-pending",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         160,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/connections/pending", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Pending Connection Requests",
				Description:   "Tracks the number of requests waiting for an available database connection over time. Non-zero values indicate the connection pool is fully utilized.",
				TitleIcon:     "Clock",
				ValueKey:      "count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-connection-timeouts",
				PanelType:     dashboardcfg.PanelType("error-rate"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         170,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/connections/timeout-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Connection Timeout Rate",
				Description:   "Tracks the rate of connection acquisition timeouts over time. Any non-zero value means requests are failing because no database connection became available in time.",
				TitleIcon:     "AlertTriangle",
				ValueKey:      "timeout_rate",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-systems",
				PanelType:     dashboardcfg.PanelType("db-systems-overview"),
				LayoutVariant: dashboardcfg.LayoutVariant("hero-detail"),
				SectionID:     "details",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/systems", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Detected Database Systems",
				Description:   "Lists all database systems detected from span attributes, with key metrics for each. Drill down into a system to see its detailed performance breakdown.",
				TitleIcon:     "Database",
				DrawerAction:  &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("databaseSystem"), IDField: "db_system", TitleField: "db_system"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-slow-queries",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "details",
				Order:         110,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/slow-queries/patterns", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Top Slow Query Patterns",
				Description:   "Lists the slowest query patterns ranked by latency. Each row represents a normalized query signature with its p99 latency and call count for optimization prioritization.",
				TitleIcon:     "AlertTriangle",
			},
			dashboardcfg.PanelDefinition{
				ID:            "db-slowest-collections",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("detail-table"),
				SectionID:     "details",
				Order:         120,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/database/slow-queries/collections", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Slowest Collections",
				Description:   "Lists database collections or tables ranked by query latency. Use this to identify which data stores need indexing or schema optimization.",
				TitleIcon:     "Table",
			},
		},
	}
}
