package saturation

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func redisTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "redis",
		PageID: "saturation",
		Label:  "Redis",
		Order:  20,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "summary", Title: "Key Metrics", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "trends", Title: "Golden Signals", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "details", Title: "Details", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "cache-hit-rate",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/cache-hit-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Cache Hit Rate",
				Description:   "Shows the percentage of key lookups that returned a cached value across all Redis instances. A declining hit rate may indicate key evictions or a shift in access patterns.",
				TitleIcon:     "Target",
				ValueField:    "hit_rate_pct",
				Formatter:     "percent1",
			},
			dashboardcfg.PanelDefinition{
				ID:            "cache-hits",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/cache-hit-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Cache Hits",
				Description:   "Shows the total number of successful cache lookups in the selected time range. Use alongside cache misses to assess overall cache effectiveness.",
				TitleIcon:     "CheckCircle",
				ValueField:    "hits",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "cache-misses",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/cache-hit-rate", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Cache Misses",
				Description:   "Shows the total number of cache lookups that did not find a key. A spike in misses can increase load on downstream databases.",
				TitleIcon:     "XCircle",
				ValueField:    "misses",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "replication-offset",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/replication-lag", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Replication Offset",
				Description:   "Shows the current replication offset between primary and replica Redis instances. A growing offset indicates replicas are falling behind the primary.",
				TitleIcon:     "GitBranch",
				ValueField:    "offset",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "redis-clients",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/clients", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Connected Clients",
				Description:   "Tracks the number of client connections to Redis over time. A sudden increase may indicate connection leaks; a drop may signal connectivity problems.",
				TitleIcon:     "Users",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "redis-memory",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         60,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/memory", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Memory Used",
				Description:   "Tracks total memory consumed by Redis over time. Watch for steady growth approaching the maxmemory limit, which triggers evictions.",
				TitleIcon:     "HardDrive",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "redis-memory-frag",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/memory-fragmentation", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Memory Fragmentation Ratio",
				Description:   "Tracks the ratio of OS-allocated memory to Redis-used memory over time. Values significantly above 1.0 indicate memory fragmentation; values below 1.0 suggest swapping.",
				TitleIcon:     "AlertTriangle",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "redis-commands",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/commands", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Commands Processed",
				Description:   "Tracks the total Redis command throughput over time. Correlate command volume with latency to distinguish load-driven slowdowns from infrastructure issues.",
				TitleIcon:     "Terminal",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "redis-evictions",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         90,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/evictions", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Key Evictions",
				Description:   "Tracks the number of keys evicted due to memory pressure over time. Non-zero evictions indicate Redis has reached its maxmemory limit and is discarding keys.",
				TitleIcon:     "Trash2",
				ValueField:    "value",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "redis-instances",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "details",
				Order:         95,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/instances", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Redis Instances",
				Description:   "Lists all detected Redis instances with summary metrics for each. Drill down into an instance to see its detailed performance and memory breakdown.",
				TitleIcon:     "Server",
				Columns: []dashboardcfg.DashboardTableColumn{
					dashboardcfg.DashboardTableColumn{Key: "instance", Label: "Instance", Align: dashboardcfg.ColumnAlign("left"), Width: dashboardcfg.IntPtr(180)},
				},
				DrawerAction: &dashboardcfg.DrawerActionSpec{Entity: dashboardcfg.DrawerEntity("redisInstance"), IDField: "instance", TitleField: "instance"},
			},
			dashboardcfg.PanelDefinition{
				ID:            "redis-keyspace",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "details",
				Order:         100,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/keyspace", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Keyspace Size by DB",
				Description:   "Shows the number of keys stored in each Redis logical database. Helps identify which databases consume the most memory and drive eviction pressure.",
				TitleIcon:     "Database",
			},
			dashboardcfg.PanelDefinition{
				ID:            "redis-key-expiries",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("detail-table"),
				SectionID:     "details",
				Order:         110,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/saturation/redis/key-expiries", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Key Expiries by DB",
				Description:   "Shows the number of expired keys per Redis logical database. A low expiry count relative to keyspace size may mean TTLs are not set, leading to unskilled memory growth.",
				TitleIcon:     "Clock",
			},
		},
	}
}
