package ai_observability

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/infra/dashboardcfg"
)

func overviewTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "overview",
		PageID: "ai-observability",
		Label:  "Overview",
		Order:  10,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "summary", Title: "Key Metrics", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "trends", Title: "Golden Signals", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "summary-total-requests",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Total Requests",
				Description:   "Shows the total number of inference requests across all LLM models. Use this to gauge overall AI workload volume.",
				TitleIcon:     "Activity",
				ValueField:    "request_count",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "summary-total-cost",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Total Cost",
				Description:   "Shows the cumulative cost in USD across all models for the selected period. Watch for sudden increases driven by token-heavy prompts or new model adoption.",
				TitleIcon:     "DollarSign",
				ValueField:    "total_cost_usd",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "summary-guardrail-blocks",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Guardrail Blocks",
				Description:   "Shows the number of inference requests blocked by safety guardrails. A rising count may indicate prompt injection attempts or policy violations.",
				TitleIcon:     "Shield",
				ValueField:    "guardrail_count",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "summary-pii-detections",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/summary", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "PII Detections",
				Description:   "Shows the number of personally identifiable information instances detected in prompts or completions. Any non-zero value requires review for data compliance.",
				TitleIcon:     "Eye",
				ValueField:    "pii_count",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "qps",
				PanelType:     dashboardcfg.PanelType("ai-line"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         50,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/performance/timeseries", Params: dashboardcfg.MustQueryParams(map[string]any{
					"interval": "5m",
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "QPS per Model",
				Description: "Tracks inference queries per second for each model over time. Identify which models handle the most traffic and spot load spikes.",
				TitleIcon:   "TrendingUp",
				GroupByKey:  "model_name",
				ValueKey:    "qps",
			},
			dashboardcfg.PanelDefinition{
				ID:            "avg-latency",
				PanelType:     dashboardcfg.PanelType("ai-line"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         60,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/performance/timeseries", Params: dashboardcfg.MustQueryParams(map[string]any{
					"interval": "5m",
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Avg Latency ms per Model",
				Description: "Shows average inference latency per model in milliseconds. Higher latency on completion-heavy requests is expected; watch for regressions.",
				TitleIcon:   "Clock",
				GroupByKey:  "model_name",
				ValueKey:    "avg_latency_ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "cost-over-time",
				PanelType:     dashboardcfg.PanelType("ai-line"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         70,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/cost/timeseries", Params: dashboardcfg.MustQueryParams(map[string]any{
					"interval": "5m",
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "Cost per Interval (USD)",
				Description: "Tracks the dollar cost of token consumption per time interval for each model. Use this to detect cost anomalies early.",
				TitleIcon:   "DollarSign",
				GroupByKey:  "model_name",
				ValueKey:    "cost_per_interval",
				YPrefix:     "$",
				YDecimals:   dashboardcfg.IntPtr(4),
			},
			dashboardcfg.PanelDefinition{
				ID:            "pii-detections",
				PanelType:     dashboardcfg.PanelType("ai-line"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         80,
				Query: dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/ai/security/timeseries", Params: dashboardcfg.MustQueryParams(map[string]any{
					"interval": "5m",
				})},
				Layout:      dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:       "PII Detections per Model",
				Description: "Tracks PII detection events over time for each model. Correlate spikes with specific prompt patterns or upstream integrations.",
				TitleIcon:   "ShieldCheck",
				GroupByKey:  "model_name",
				ValueKey:    "pii_count",
			},
		},
	}
}
