// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: log_row.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Row is the wire format on Kafka. One record == one log row bound for
// observability.logs. The field order mirrors the ClickHouse column order
// declared in row.go Columns so the consumer can build positional CH values
// without a lookup map. The legacy `scope_string` field was removed in the
// ingest rewrite — it duplicated `scope_name` and added no query value.
type Row struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TeamId              uint32                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TsBucketStart       uint32                 `protobuf:"varint,2,opt,name=ts_bucket_start,json=tsBucketStart,proto3" json:"ts_bucket_start,omitempty"`
	TimestampNs         int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // time.Time at CH boundary
	ObservedTimestampNs uint64                 `protobuf:"varint,4,opt,name=observed_timestamp_ns,json=observedTimestampNs,proto3" json:"observed_timestamp_ns,omitempty"`
	TraceId             string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId              string                 `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceFlags          uint32                 `protobuf:"varint,7,opt,name=trace_flags,json=traceFlags,proto3" json:"trace_flags,omitempty"`
	SeverityText        string                 `protobuf:"bytes,8,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	SeverityNumber      uint32                 `protobuf:"varint,9,opt,name=severity_number,json=severityNumber,proto3" json:"severity_number,omitempty"` // uint8 at CH; narrow at boundary
	Body                string                 `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	AttributesString    map[string]string      `protobuf:"bytes,11,rep,name=attributes_string,json=attributesString,proto3" json:"attributes_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AttributesNumber    map[string]float64     `protobuf:"bytes,12,rep,name=attributes_number,json=attributesNumber,proto3" json:"attributes_number,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	AttributesBool      map[string]bool        `protobuf:"bytes,13,rep,name=attributes_bool,json=attributesBool,proto3" json:"attributes_bool,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Resource            map[string]string      `protobuf:"bytes,14,rep,name=resource,proto3" json:"resource,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceFingerprint string                 `protobuf:"bytes,15,opt,name=resource_fingerprint,json=resourceFingerprint,proto3" json:"resource_fingerprint,omitempty"`
	ScopeName           string                 `protobuf:"bytes,16,opt,name=scope_name,json=scopeName,proto3" json:"scope_name,omitempty"`
	ScopeVersion        string                 `protobuf:"bytes,17,opt,name=scope_version,json=scopeVersion,proto3" json:"scope_version,omitempty"` // field 18 (scope_string) intentionally retired.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_log_row_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_log_row_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_log_row_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetTeamId() uint32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Row) GetTsBucketStart() uint32 {
	if x != nil {
		return x.TsBucketStart
	}
	return 0
}

func (x *Row) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Row) GetObservedTimestampNs() uint64 {
	if x != nil {
		return x.ObservedTimestampNs
	}
	return 0
}

func (x *Row) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Row) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Row) GetTraceFlags() uint32 {
	if x != nil {
		return x.TraceFlags
	}
	return 0
}

func (x *Row) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *Row) GetSeverityNumber() uint32 {
	if x != nil {
		return x.SeverityNumber
	}
	return 0
}

func (x *Row) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Row) GetAttributesString() map[string]string {
	if x != nil {
		return x.AttributesString
	}
	return nil
}

func (x *Row) GetAttributesNumber() map[string]float64 {
	if x != nil {
		return x.AttributesNumber
	}
	return nil
}

func (x *Row) GetAttributesBool() map[string]bool {
	if x != nil {
		return x.AttributesBool
	}
	return nil
}

func (x *Row) GetResource() map[string]string {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Row) GetResourceFingerprint() string {
	if x != nil {
		return x.ResourceFingerprint
	}
	return ""
}

func (x *Row) GetScopeName() string {
	if x != nil {
		return x.ScopeName
	}
	return ""
}

func (x *Row) GetScopeVersion() string {
	if x != nil {
		return x.ScopeVersion
	}
	return ""
}

var File_log_row_proto protoreflect.FileDescriptor

const file_log_row_proto_rawDesc = "" +
	"\n" +
	"\rlog_row.proto\x12\x15optikk.ingest.logs.v1\"\xb2\b\n" +
	"\x03Row\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\rR\x06teamId\x12&\n" +
	"\x0fts_bucket_start\x18\x02 \x01(\rR\rtsBucketStart\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x122\n" +
	"\x15observed_timestamp_ns\x18\x04 \x01(\x04R\x13observedTimestampNs\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\x12\x1f\n" +
	"\vtrace_flags\x18\a \x01(\rR\n" +
	"traceFlags\x12#\n" +
	"\rseverity_text\x18\b \x01(\tR\fseverityText\x12'\n" +
	"\x0fseverity_number\x18\t \x01(\rR\x0eseverityNumber\x12\x12\n" +
	"\x04body\x18\n" +
	" \x01(\tR\x04body\x12]\n" +
	"\x11attributes_string\x18\v \x03(\v20.optikk.ingest.logs.v1.Row.AttributesStringEntryR\x10attributesString\x12]\n" +
	"\x11attributes_number\x18\f \x03(\v20.optikk.ingest.logs.v1.Row.AttributesNumberEntryR\x10attributesNumber\x12W\n" +
	"\x0fattributes_bool\x18\r \x03(\v2..optikk.ingest.logs.v1.Row.AttributesBoolEntryR\x0eattributesBool\x12D\n" +
	"\bresource\x18\x0e \x03(\v2(.optikk.ingest.logs.v1.Row.ResourceEntryR\bresource\x121\n" +
	"\x14resource_fingerprint\x18\x0f \x01(\tR\x13resourceFingerprint\x12\x1d\n" +
	"\n" +
	"scope_name\x18\x10 \x01(\tR\tscopeName\x12#\n" +
	"\rscope_version\x18\x11 \x01(\tR\fscopeVersion\x1aC\n" +
	"\x15AttributesStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15AttributesNumberEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aA\n" +
	"\x13AttributesBoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a;\n" +
	"\rResourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BCZAgithub.com/Optikk-Org/optikk-backend/internal/ingestion/logs;logsb\x06proto3"

var (
	file_log_row_proto_rawDescOnce sync.Once
	file_log_row_proto_rawDescData []byte
)

func file_log_row_proto_rawDescGZIP() []byte {
	file_log_row_proto_rawDescOnce.Do(func() {
		file_log_row_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_row_proto_rawDesc), len(file_log_row_proto_rawDesc)))
	})
	return file_log_row_proto_rawDescData
}

var file_log_row_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_log_row_proto_goTypes = []any{
	(*Row)(nil), // 0: optikk.ingest.logs.v1.Row
	nil,         // 1: optikk.ingest.logs.v1.Row.AttributesStringEntry
	nil,         // 2: optikk.ingest.logs.v1.Row.AttributesNumberEntry
	nil,         // 3: optikk.ingest.logs.v1.Row.AttributesBoolEntry
	nil,         // 4: optikk.ingest.logs.v1.Row.ResourceEntry
}
var file_log_row_proto_depIdxs = []int32{
	1, // 0: optikk.ingest.logs.v1.Row.attributes_string:type_name -> optikk.ingest.logs.v1.Row.AttributesStringEntry
	2, // 1: optikk.ingest.logs.v1.Row.attributes_number:type_name -> optikk.ingest.logs.v1.Row.AttributesNumberEntry
	3, // 2: optikk.ingest.logs.v1.Row.attributes_bool:type_name -> optikk.ingest.logs.v1.Row.AttributesBoolEntry
	4, // 3: optikk.ingest.logs.v1.Row.resource:type_name -> optikk.ingest.logs.v1.Row.ResourceEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_log_row_proto_init() }
func file_log_row_proto_init() {
	if File_log_row_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_row_proto_rawDesc), len(file_log_row_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_log_row_proto_goTypes,
		DependencyIndexes: file_log_row_proto_depIdxs,
		MessageInfos:      file_log_row_proto_msgTypes,
	}.Build()
	File_log_row_proto = out.File
	file_log_row_proto_goTypes = nil
	file_log_row_proto_depIdxs = nil
}
