apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      server: clickhouse
      port: 9000
      username: default
      defaultDatabase: observability
    secureJsonData:
      password: clickhouse123
    editable: false
