// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: span_row.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Row is the wire format on Kafka. One record == one span row bound for
// observability.spans. Field order mirrors the ClickHouse column order in
// row.go Columns so the consumer can produce positional CH values with no
// name lookup.
type Row struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TsBucketStart       uint64                 `protobuf:"varint,1,opt,name=ts_bucket_start,json=tsBucketStart,proto3" json:"ts_bucket_start,omitempty"`
	TeamId              uint32                 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TimestampNs         int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	TraceId             string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId              string                 `protobuf:"bytes,5,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId        string                 `protobuf:"bytes,6,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	TraceState          string                 `protobuf:"bytes,7,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	Flags               uint32                 `protobuf:"varint,8,opt,name=flags,proto3" json:"flags,omitempty"`
	Name                string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Kind                int32                  `protobuf:"varint,10,opt,name=kind,proto3" json:"kind,omitempty"` // int8 at CH
	KindString          string                 `protobuf:"bytes,11,opt,name=kind_string,json=kindString,proto3" json:"kind_string,omitempty"`
	DurationNano        uint64                 `protobuf:"varint,12,opt,name=duration_nano,json=durationNano,proto3" json:"duration_nano,omitempty"`
	HasError            bool                   `protobuf:"varint,13,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	IsRemote            bool                   `protobuf:"varint,14,opt,name=is_remote,json=isRemote,proto3" json:"is_remote,omitempty"`
	StatusCode          int32                  `protobuf:"varint,15,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // int16 at CH
	StatusCodeString    string                 `protobuf:"bytes,16,opt,name=status_code_string,json=statusCodeString,proto3" json:"status_code_string,omitempty"`
	StatusMessage       string                 `protobuf:"bytes,17,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	HttpUrl             string                 `protobuf:"bytes,18,opt,name=http_url,json=httpUrl,proto3" json:"http_url,omitempty"`
	HttpMethod          string                 `protobuf:"bytes,19,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	HttpHost            string                 `protobuf:"bytes,20,opt,name=http_host,json=httpHost,proto3" json:"http_host,omitempty"`
	ExternalHttpUrl     string                 `protobuf:"bytes,21,opt,name=external_http_url,json=externalHttpUrl,proto3" json:"external_http_url,omitempty"`
	ExternalHttpMethod  string                 `protobuf:"bytes,22,opt,name=external_http_method,json=externalHttpMethod,proto3" json:"external_http_method,omitempty"`
	ResponseStatusCode  string                 `protobuf:"bytes,23,opt,name=response_status_code,json=responseStatusCode,proto3" json:"response_status_code,omitempty"`
	Attributes          map[string]string      `protobuf:"bytes,24,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Events              []string               `protobuf:"bytes,25,rep,name=events,proto3" json:"events,omitempty"`
	Links               string                 `protobuf:"bytes,26,opt,name=links,proto3" json:"links,omitempty"`
	ExceptionType       string                 `protobuf:"bytes,27,opt,name=exception_type,json=exceptionType,proto3" json:"exception_type,omitempty"`
	ExceptionMessage    string                 `protobuf:"bytes,28,opt,name=exception_message,json=exceptionMessage,proto3" json:"exception_message,omitempty"`
	ExceptionStacktrace string                 `protobuf:"bytes,29,opt,name=exception_stacktrace,json=exceptionStacktrace,proto3" json:"exception_stacktrace,omitempty"`
	ExceptionEscaped    bool                   `protobuf:"varint,30,opt,name=exception_escaped,json=exceptionEscaped,proto3" json:"exception_escaped,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_span_row_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_span_row_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_span_row_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetTsBucketStart() uint64 {
	if x != nil {
		return x.TsBucketStart
	}
	return 0
}

func (x *Row) GetTeamId() uint32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Row) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Row) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Row) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Row) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Row) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

func (x *Row) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Row) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Row) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Row) GetKindString() string {
	if x != nil {
		return x.KindString
	}
	return ""
}

func (x *Row) GetDurationNano() uint64 {
	if x != nil {
		return x.DurationNano
	}
	return 0
}

func (x *Row) GetHasError() bool {
	if x != nil {
		return x.HasError
	}
	return false
}

func (x *Row) GetIsRemote() bool {
	if x != nil {
		return x.IsRemote
	}
	return false
}

func (x *Row) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Row) GetStatusCodeString() string {
	if x != nil {
		return x.StatusCodeString
	}
	return ""
}

func (x *Row) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *Row) GetHttpUrl() string {
	if x != nil {
		return x.HttpUrl
	}
	return ""
}

func (x *Row) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *Row) GetHttpHost() string {
	if x != nil {
		return x.HttpHost
	}
	return ""
}

func (x *Row) GetExternalHttpUrl() string {
	if x != nil {
		return x.ExternalHttpUrl
	}
	return ""
}

func (x *Row) GetExternalHttpMethod() string {
	if x != nil {
		return x.ExternalHttpMethod
	}
	return ""
}

func (x *Row) GetResponseStatusCode() string {
	if x != nil {
		return x.ResponseStatusCode
	}
	return ""
}

func (x *Row) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Row) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Row) GetLinks() string {
	if x != nil {
		return x.Links
	}
	return ""
}

func (x *Row) GetExceptionType() string {
	if x != nil {
		return x.ExceptionType
	}
	return ""
}

func (x *Row) GetExceptionMessage() string {
	if x != nil {
		return x.ExceptionMessage
	}
	return ""
}

func (x *Row) GetExceptionStacktrace() string {
	if x != nil {
		return x.ExceptionStacktrace
	}
	return ""
}

func (x *Row) GetExceptionEscaped() bool {
	if x != nil {
		return x.ExceptionEscaped
	}
	return false
}

var File_span_row_proto protoreflect.FileDescriptor

const file_span_row_proto_rawDesc = "" +
	"\n" +
	"\x0espan_row.proto\x12\x16optikk.ingest.spans.v1\"\xef\b\n" +
	"\x03Row\x12&\n" +
	"\x0fts_bucket_start\x18\x01 \x01(\x04R\rtsBucketStart\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\rR\x06teamId\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x05 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x06 \x01(\tR\fparentSpanId\x12\x1f\n" +
	"\vtrace_state\x18\a \x01(\tR\n" +
	"traceState\x12\x14\n" +
	"\x05flags\x18\b \x01(\rR\x05flags\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\n" +
	" \x01(\x05R\x04kind\x12\x1f\n" +
	"\vkind_string\x18\v \x01(\tR\n" +
	"kindString\x12#\n" +
	"\rduration_nano\x18\f \x01(\x04R\fdurationNano\x12\x1b\n" +
	"\thas_error\x18\r \x01(\bR\bhasError\x12\x1b\n" +
	"\tis_remote\x18\x0e \x01(\bR\bisRemote\x12\x1f\n" +
	"\vstatus_code\x18\x0f \x01(\x05R\n" +
	"statusCode\x12,\n" +
	"\x12status_code_string\x18\x10 \x01(\tR\x10statusCodeString\x12%\n" +
	"\x0estatus_message\x18\x11 \x01(\tR\rstatusMessage\x12\x19\n" +
	"\bhttp_url\x18\x12 \x01(\tR\ahttpUrl\x12\x1f\n" +
	"\vhttp_method\x18\x13 \x01(\tR\n" +
	"httpMethod\x12\x1b\n" +
	"\thttp_host\x18\x14 \x01(\tR\bhttpHost\x12*\n" +
	"\x11external_http_url\x18\x15 \x01(\tR\x0fexternalHttpUrl\x120\n" +
	"\x14external_http_method\x18\x16 \x01(\tR\x12externalHttpMethod\x120\n" +
	"\x14response_status_code\x18\x17 \x01(\tR\x12responseStatusCode\x12K\n" +
	"\n" +
	"attributes\x18\x18 \x03(\v2+.optikk.ingest.spans.v1.Row.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06events\x18\x19 \x03(\tR\x06events\x12\x14\n" +
	"\x05links\x18\x1a \x01(\tR\x05links\x12%\n" +
	"\x0eexception_type\x18\x1b \x01(\tR\rexceptionType\x12+\n" +
	"\x11exception_message\x18\x1c \x01(\tR\x10exceptionMessage\x121\n" +
	"\x14exception_stacktrace\x18\x1d \x01(\tR\x13exceptionStacktrace\x12+\n" +
	"\x11exception_escaped\x18\x1e \x01(\bR\x10exceptionEscaped\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BEZCgithub.com/Optikk-Org/optikk-backend/internal/ingestion/spans;spansb\x06proto3"

var (
	file_span_row_proto_rawDescOnce sync.Once
	file_span_row_proto_rawDescData []byte
)

func file_span_row_proto_rawDescGZIP() []byte {
	file_span_row_proto_rawDescOnce.Do(func() {
		file_span_row_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_span_row_proto_rawDesc), len(file_span_row_proto_rawDesc)))
	})
	return file_span_row_proto_rawDescData
}

var file_span_row_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_span_row_proto_goTypes = []any{
	(*Row)(nil), // 0: optikk.ingest.spans.v1.Row
	nil,         // 1: optikk.ingest.spans.v1.Row.AttributesEntry
}
var file_span_row_proto_depIdxs = []int32{
	1, // 0: optikk.ingest.spans.v1.Row.attributes:type_name -> optikk.ingest.spans.v1.Row.AttributesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_span_row_proto_init() }
func file_span_row_proto_init() {
	if File_span_row_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_span_row_proto_rawDesc), len(file_span_row_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_span_row_proto_goTypes,
		DependencyIndexes: file_span_row_proto_depIdxs,
		MessageInfos:      file_span_row_proto_msgTypes,
	}.Build()
	File_span_row_proto = out.File
	file_span_row_proto_goTypes = nil
	file_span_row_proto_depIdxs = nil
}
