package infrastructure

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/platform/dashboardcfg"
)

func kubernetesTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "kubernetes",
		PageID: "infrastructure",
		Label:  "Kubernetes",
		Order:  30,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "summary", Title: "Key Metrics", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "trends", Title: "Golden Signals", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
			dashboardcfg.SectionDefinition{ID: "breakdowns", Title: "Breakdowns", Order: 30, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("three-up")},
			dashboardcfg.SectionDefinition{ID: "details", Title: "Details", Order: 40, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("table-stack")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "allocatable-cpu-(cores)",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/node-allocatable", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Allocatable CPU (cores)",
				Description:   "Shows the total allocatable CPU cores across all Kubernetes nodes. Compare against requested CPU to gauge cluster headroom.",
				TitleIcon:     "Cpu",
				ValueField:    "cpu_cores",
				Formatter:     "number",
			},
			dashboardcfg.PanelDefinition{
				ID:            "allocatable-memory",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/node-allocatable", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Allocatable Memory",
				Description:   "Shows the total allocatable memory across all Kubernetes nodes. Low headroom may prevent new pod scheduling.",
				TitleIcon:     "HardDrive",
				ValueField:    "memory_bytes",
				Formatter:     "bytes",
			},
			dashboardcfg.PanelDefinition{
				ID:            "k8s-container-cpu",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/container-cpu", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Container CPU Time",
				Description:   "Tracks CPU time consumed by each container over time. Containers consistently near their CPU limits are candidates for throttling.",
				TitleIcon:     "Cpu",
				GroupByKey:    "container",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "k8s-cpu-throttling",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/cpu-throttling", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "CPU Throttling Time",
				Description:   "Shows the time containers spent being CPU-throttled by the kernel. Non-zero throttling means containers are hitting their CPU limits.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "container",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "k8s-container-memory",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/container-memory", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Container Memory Usage",
				Description:   "Tracks memory consumption per container over time. Containers approaching their memory limits risk being OOM-killed.",
				TitleIcon:     "HardDrive",
				GroupByKey:    "container",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "k8s-oom-kills",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         60,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/oom-kills", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "OOM Kill Count",
				Description:   "Shows the number of out-of-memory kills per container. Any OOM kills indicate that memory limits need to be increased or the application has a leak.",
				TitleIcon:     "AlertTriangle",
				GroupByKey:    "container",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "k8s-pod-phases",
				PanelType:     dashboardcfg.PanelType("pie"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary"),
				SectionID:     "breakdowns",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/pod-phases", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Pod Phase Distribution",
				Description:   "Displays the distribution of pods across phases such as Running, Pending, and Failed. A high Pending count suggests scheduling or resource constraints.",
				TitleIcon:     "Circle",
				GroupByKey:    "phase",
				ValueKey:      "count",
			},
			dashboardcfg.PanelDefinition{
				ID:            "k8s-replica-status",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "details",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/replica-status", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "ReplicaSet Status (Desired vs Available)",
				Description:   "Compares desired versus available replicas for each deployment. A mismatch indicates pods that failed to schedule or start.",
				TitleIcon:     "Layers",
			},
			dashboardcfg.PanelDefinition{
				ID:            "k8s-pod-restarts",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("summary-table"),
				SectionID:     "details",
				Order:         90,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/pod-restarts", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Pod Restarts",
				Description:   "Lists pods ranked by restart count. Frequent restarts point to crash loops, health-check failures, or resource limits being exceeded.",
				TitleIcon:     "RefreshCw",
			},
			dashboardcfg.PanelDefinition{
				ID:            "k8s-volume-usage",
				PanelType:     dashboardcfg.PanelType("table"),
				LayoutVariant: dashboardcfg.LayoutVariant("detail-table"),
				SectionID:     "details",
				Order:         100,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/kubernetes/volume-usage", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Volume Usage",
				Description:   "Shows persistent volume capacity and current usage per claim. Volumes nearing full capacity may cause application write failures.",
				TitleIcon:     "FolderOpen",
			},
		},
	}
}
