package infrastructure

import (
	dashboardcfg "github.com/Optikk-Org/optikk-backend/internal/platform/dashboardcfg"
)

func jvmTab() dashboardcfg.TabDefinition {
	return dashboardcfg.TabDefinition{
		ID:     "jvm",
		PageID: "infrastructure",
		Label:  "JVM Runtime",
		Order:  20,
		Sections: []dashboardcfg.SectionDefinition{
			dashboardcfg.SectionDefinition{ID: "summary", Title: "Key Metrics", Order: 10, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("kpi-band")},
			dashboardcfg.SectionDefinition{ID: "trends", Title: "Golden Signals", Order: 20, Collapsible: true, SectionTemplate: dashboardcfg.SectionTemplate("two-up")},
		},
		Panels: []dashboardcfg.PanelDefinition{
			dashboardcfg.PanelDefinition{
				ID:            "gc-p95-duration",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         10,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/gc-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "GC p95 Duration",
				Description:   "Shows the 95th-percentile garbage collection pause duration. Elevated values indicate GC pressure that may cause application latency spikes.",
				TitleIcon:     "Trash2",
				ValueField:    "p95",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "gc-p99-duration",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         20,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/gc-duration", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "GC p99 Duration",
				Description:   "Shows the 99th-percentile garbage collection pause duration. Tail-latency GC pauses here directly impact worst-case response times.",
				TitleIcon:     "Trash2",
				ValueField:    "p99",
				Formatter:     "ms",
			},
			dashboardcfg.PanelDefinition{
				ID:            "jvm-cpu-time",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         30,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/cpu", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "JVM CPU Time",
				Description:   "Shows the total CPU time consumed by the JVM process. Compare against host CPU capacity to gauge JVM overhead.",
				TitleIcon:     "Cpu",
				ValueField:    "cpu_time_value",
				Formatter:     "ns",
			},
			dashboardcfg.PanelDefinition{
				ID:            "jvm-cpu-utilization",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         40,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/cpu", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "JVM CPU Utilization",
				Description:   "Shows the recent CPU utilization of the JVM process as a percentage. Sustained high values may require scaling or code optimization.",
				TitleIcon:     "Cpu",
				ValueField:    "recent_utilization",
				Formatter:     "percent2",
			},
			dashboardcfg.PanelDefinition{
				ID:            "jvm-classes",
				PanelType:     dashboardcfg.PanelType("stat-card"),
				LayoutVariant: dashboardcfg.LayoutVariant("kpi"),
				SectionID:     "summary",
				Order:         90,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/classes", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Loaded Classes",
				Description:   "Shows the number of classes currently loaded in the JVM. A continuously increasing count may indicate a classloader leak.",
				TitleIcon:     "BookOpen",
				ValueField:    "loaded",
			},
			dashboardcfg.PanelDefinition{
				ID:            "jvm-memory",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         50,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/memory", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "JVM Memory (Used / Committed / Limit)",
				Description:   "Tracks heap and non-heap memory pools showing used, committed, and max limits. Watch for used memory approaching the limit, which triggers aggressive GC.",
				TitleIcon:     "HardDrive",
				GroupByKey:    "pool_name",
				ValueKey:      "used",
			},
			dashboardcfg.PanelDefinition{
				ID:            "jvm-gc-collections",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         60,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/gc-collections", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "GC Collections by Collector",
				Description:   "Shows garbage collection invocation counts grouped by collector type. Frequent full GC cycles suggest heap sizing or memory leak issues.",
				TitleIcon:     "Trash2",
				GroupByKey:    "collector",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "jvm-threads",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         70,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/threads", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Thread Count by Daemon Status",
				Description:   "Tracks JVM thread counts grouped by daemon versus non-daemon threads. A sudden increase can indicate thread leaks or runaway background work.",
				TitleIcon:     "Activity",
				GroupByKey:    "daemon",
				ValueKey:      "value",
			},
			dashboardcfg.PanelDefinition{
				ID:            "jvm-buffers",
				PanelType:     dashboardcfg.PanelType("request"),
				LayoutVariant: dashboardcfg.LayoutVariant("standard-chart"),
				SectionID:     "trends",
				Order:         80,
				Query:         dashboardcfg.QuerySpec{Method: "GET", Endpoint: "/v1/infrastructure/jvm/buffers", Params: nil},
				Layout:        dashboardcfg.PanelLayout{X: 0, Y: 0, W: 0, H: 0},
				Title:         "Buffer Pool Memory Usage",
				Description:   "Shows direct and mapped buffer pool memory consumption. Rising buffer usage without release may indicate NIO resource leaks.",
				TitleIcon:     "Database",
				GroupByKey:    "pool_name",
				ValueKey:      "memory_usage",
			},
		},
	}
}
